### ISSUE TITLE
Audio/video not synchronized

### ISSUE THREAD

**Issue by salleman33** [aau-zid/BigBlueButton-liveStreaming#100]
**Describe the bug**
Hi, 
Audio and video are not sync. Audio is ~3 second early. 

**To Reproduce**
just launch docker image and play rtmp stream

**Expected behavior**
audio and video are synchronized

**Desktop (please complete the following information):**
 - Docker host is a debian 10 with  32Go ram and 16 CPU
 - my stream server is the same host

thanks for your help

**Comment by salleman33** [comment]
Ok, i add an offset to resolve my problem : 
new ffmpeg options with "itsoffset 1.5" on pulseaudio stream : 
`ffmpeg_stream = 'ffmpeg -thread_queue_size "%s" -f x11grab -draw_mouse 0 -s %s  -i :%d -thread_queue_size "%s" -f pulse -itsoffset 1.5 -i default -ac 2 %s -f flv -flvflags no_duration_filesize "%s"' `

**Comment by mtsonline** [comment]
thanks for the fix example. hopefully this can help others that experience this. cheers
