### ISSUE TITLE
 I can't connect the live stream meeting

### ISSUE THREAD

**Issue by jmbarroso84** [aau-zid/BigBlueButton-liveStreaming#101]
Good afternoon,

Sorry for putting this request for help here, but there was no specific forum for it. If I have to delete it, you just have to tell me.

I have tried to start live streaming with youtube through bigbluebutton, but after doing the required settings and starting livestreaming, it seems that it does not connect with youtube or bigbluebutton.

I have configured the secret key, the BBB_URL, the BBB_MEETING_ID, the BBB_SECRET and the BBB_STREAM_URL with the youtube address (rtmp: //a.rtmp.youtube.com/live2) and the youtube stream key.

But from many tests I have done, I cannot get it to work. Could you help me to solve it? I would appreciate it from the heart.

Congratulations on the excellent job you have done.

A hug.

P.s: Sorry for my English

**Comment by mtsonline** [comment]
Hi,


you're welcome - and your english is completely okay :-)

Does the live user connect to your meeting? Can you see it in the users 
list in the meeting room?

Did you start the meeting before starting the live Streaming?


what do you get with docker logs <containername>?

(you also could start with docker-compose up (without -d) to see the log 
output directly.


if the live user is connected and stays in the room - you would have to 
recheck your youtube link.


cheers

Martin



Am 21.01.2021 um 00:10 schrieb jmbarroso84:

**Comment by jmbarroso84** [comment]
Good morning Martin

Thank you very much for the help.

**Does the live user connect to your meeting?**
Yes.
**Can you see it in the users list in the meeting room?**
Yes, but two minutes after the live user enters, he leaves the room.

**Did you start the meeting before starting the live Streaming?**

Yes. First I open the meeting and then I run docker-compose up -d. The answer is:
 "Creating network" root default "with the default driver.
Creating liveStreaming ... done "

When i made docker-compose up, the results is:
{"log":"Starting pulseaudio...\n","stream":"stdout","time":"2021-01-21T09:01:16.759186274Z"}
{"log":"Waiting for pulseaudio to start...\n","stream":"stdout","time":"2021-01-21T09:01:16.768502658Z"}
{"log":"INFO:root:Starting browser!!\n","stream":"stdout","time":"2021-01-21T09:01:18.231809838Z"}
{"log":"INFO:root:streaming intro...\n","stream":"stdout","time":"2021-01-21T09:01:20.006013946Z"}
{"log":"ffmpeg version 4.3.1-0york0~18.04 Copyright (c) 2000-2020 the FFmpeg developers\n","stream":"stdout","time":"2021-01-21T09:01:20.112048621Z"}
{"log":"  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)\n","stream":"stdout","time":"2021-01-21T09:01:20.112081222Z"}
{"log":"  configuration: --prefix=/usr --extra-version='0york0~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libzimg --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n","stream":"stdout","time":"2021-01-21T09:01:20.112093522Z"}
{"log":"  libavutil      56. 51.100 / 56. 51.100\n","stream":"stdout","time":"2021-01-21T09:01:20.112108823Z"}
{"log":"  libavcodec     58. 91.100 / 58. 91.100\n","stream":"stdout","time":"2021-01-21T09:01:20.112112023Z"}
{"log":"  libavformat    58. 45.100 / 58. 45.100\n","stream":"stdout","time":"2021-01-21T09:01:20.112115023Z"}
{"log":"  libavdevice    58. 10.100 / 58. 10.100\n","stream":"stdout","time":"2021-01-21T09:01:20.112118023Z"}
{"log":"  libavfilter     7. 85.100 /  7. 85.100\n","stream":"stdout","time":"2021-01-21T09:01:20.112121023Z"}
{"log":"  libavresample   4.  0.  0 /  4.  0.  0\n","stream":"stdout","time":"2021-01-21T09:01:20.112123823Z"}
{"log":"  libswscale      5.  7.100 /  5.  7.100\n","stream":"stdout","time":"2021-01-21T09:01:20.112126623Z"}
{"log":"  libswresample   3.  7.100 /  3.  7.100\n","stream":"stdout","time":"2021-01-21T09:01:20.112129423Z"}
{"log":"  libpostproc    55.  7.100 / 55.  7.100\n","stream":"stdout","time":"2021-01-21T09:01:20.112132223Z"}
{"log":"false: No such file or directory\n","stream":"stdout","time":"2021-01-21T09:01:20.117638531Z"}
{"log":"INFO:root:Open BBB and hide elements!!\n","stream":"stdout","time":"2021-01-21T09:01:20.124886473Z"}
{"log":"INFO:root:get_join_url...\n","stream":"stdout","time":"2021-01-21T09:01:20.124932174Z"}
{"log":"INFO:root:https://bbb.iberoamericasocial.com/bigbluebutton/api/join?meetingID=1123e354088197bdbd1c7ade52cb5c6330234244\u0026fullName=Live\u0026password=WzuhjGzpNQWO\u0026userdata-bbb_auto_join_audio=true\u0026userdata-bbb_enable_video=true\u0026userdata-bbb_listen_only_mode=true\u0026userdata-bbb_force_listen_only=true\u0026userdata-bbb_skip_check_audio=true\u0026joinViaHtml5=true\u0026checksum=3569c2cab66edbeae56ccd4773e0079af70cbdba\n","stream":"stdout","time":"2021-01-21T09:01:20.190777163Z"}

**if the live user is connected and stays in the room - you would have to recheck your youtube link.**

In the docker-compose.yml, in BBB_STREAM_URL, i have: rtmp://a.rtmp.youtube.com/live2/{my youtube stream key}

Thank you very much for your kind help, Martin. I'm not an expert, but i'm trying to learn.

Have a nice day.

Hugs.

**Comment by mtsonline** [comment]
Hi,


can you please comment the intro parameter in your config - if you do 
not want to stream an intro?


Does your log end with the join link? theree should be at least some 
more lines...


Am 21.01.2021 um 10:09 schrieb jmbarroso84:

**Comment by jmbarroso84** [comment]
Hi, Martin,

I have commented on the different parameters for the intro.

This is the log of the container after restarting it:

{"log":"Starting pulseaudio...\n","stream":"stdout","time":"2021-01-21T10:07:56.763083883Z"}
{"log":"INFO:root:Starting browser!!\n","stream":"stdout","time":"2021-01-21T10:07:57.325088785Z"}
{"log":"INFO:root:Open BBB and hide elements!!\n","stream":"stdout","time":"2021-01-21T10:07:59.111561126Z"}
{"log":"INFO:root:get_join_url...\n","stream":"stdout","time":"2021-01-21T10:07:59.111602527Z"}
{"log":"INFO:root:https://bbb.iberoamericasocial.com/bigbluebutton/api/join?meetingID=1123e354088197bdbd1c7ade52cb5c6330234244\u0026fullName=Live\u0026password=WzuhjGzpNQWO\u0026userdata-bbb_auto_join_audio=true\u0026userdata-bbb_enable_video=true\u0026userdata-bbb_listen_only_mode=true\u0026userdata-bbb_force_listen_only=true\u0026userdata-bbb_skip_check_audio=true\u0026joinViaHtml5=true\u0026checksum=3569c2cab66edbeae56ccd4773e0079af70cbdba\n","stream":"stdout","time":"2021-01-21T10:07:59.141746935Z"}
{"log":"Traceback (most recent call last):\n","stream":"stdout","time":"2021-01-21T10:08:31.415544199Z"}
{"log":"  File \"stream.py\", line 241, in \u003cmodule\u003e\n","stream":"stdout","time":"2021-01-21T10:08:31.415702404Z"}
{"log":"    bbb_browser()\n","stream":"stdout","time":"2021-01-21T10:08:31.415719005Z"}
{"log":"  File \"stream.py\", line 134, in bbb_browser\n","stream":"stdout","time":"2021-01-21T10:08:31.415725905Z"}
{"log":"    WebDriverWait(browser, selenium_timeout).until(element)\n","stream":"stdout","time":"2021-01-21T10:08:31.415730305Z"}
{"log":"  File \"/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py\", line 80, in until\n","stream":"stdout","time":"2021-01-21T10:08:31.415737905Z"}
{"log":"    raise TimeoutException(message, screen, stacktrace)\n","stream":"stdout","time":"2021-01-21T10:08:31.415743205Z"}
{"log":"selenium.common.exceptions.TimeoutException: Message: \n","stream":"stdout","time":"2021-01-21T10:08:31.415746806Z"}
{"log":"\n","stream":"stdout","time":"2021-01-21T10:08:31.415754106Z"}

Thank you very much for your speed and your help, Martin. From the heart

A hug.

**Comment by jmbarroso84** [comment]
Martin,

If you need me to share any information, you just have to tell me.

Thanks a lot.

**Comment by mtsonline** [comment]
ok. this makes more sense - a selenium timeout is most likely due to a 
missing element.

Can you please open the join url manually in a private browser window 
(incognito) and see what you get?

Did you do any special settings on this bbb system? with the default 
settings this should not happen ...


Am 21.01.2021 um 11:16 schrieb jmbarroso84:

**Comment by jmbarroso84** [comment]
When i open in a private browser window the join url (https://bbb.iberoamericasocial.com/bigbluebutton/api/join?meetingID=1123e354088197bdbd1c7ade52cb5c6330234244\u0026fullName=Live\u0026password=WzuhjGzpNQWO\u0026userdata-bbb_auto_join_audio=true\u0026userdata-bbb_enable_video=true\u0026userdata-bbb_listen_only_mode=true\u0026userdata-bbb_force_listen_only=true\u0026userdata-bbb_skip_check_audio=true\u0026joinViaHtml5=true\u0026checksum=3569c2cab66edbeae56ccd4773e0079af70cbdba\n).

Edited: When i access this link, the browser takes me to bbb main page.

When i open in a private browser window  the join url from the meeting (https://bbb.iberoamericasocial.com/b/for-3hm-x22), i access without problems.


I have no special settings in bbb, beyond changing the cover in greenlight and lowering the quality of the resolution of the cameras.

Could it be any of those things?

Thank you very much Martin.

A hug.

**Comment by mtsonline** [comment]
Error 400 can't be the case for the streaming, because then it could not 
be shown in the users list.

You may not have permissions from the location you try with your browser?

Could you check that?

You should be able to login with this link, otherwise there is some 
problem with permissions or routings / firewall and so on...


you could try to comment the redirect to /b if you have enabled this in 
the nginx config - this could interfear



Am 21.01.2021 um 12:03 schrieb jmbarroso84:

**Comment by jmbarroso84** [comment]
Sorry Martin,

just when i sending the message I edited it, because it really is not a 400 error. It was an error when copying and pasting the link. The link actually takes me to the main greenlight page in my bbb.

Do you want me to try committing the / b redirect?

Another question... could i invite you a coffee for the project??

Thank you very much for the pacience.

**Comment by mtsonline** [comment]
Hi,

it should not take you to greenlight - it should open bbb directly - so 
you will have to remove your redirect or modify it to ignore urls that 
go to the join location.


thanks, very kind of you :-)


Am 21.01.2021 um 12:23 schrieb jmbarroso84:

**Comment by jmbarroso84** [comment]
Thanks again, Martin.

I have deleted the a / b redirect in / etc / nginx / sites-available / bigbluebutton

BBB works perfectly, but now when I hit the join meeting link, I have a 403 error.

In the bar of the browser say:

https://bbb.iberoamericasocial.com/?errors=[%7B"message":"You%20did%20not%20pass%20the%20checksum%20security%20check","key":"checksumError"%7D]

Is that strange?

Wasn't kidding about the coffee, do you have paypal?

A hug.

**Comment by mtsonline** [comment]
the checksum is automatically generated - and seems to work as the live 
user can join the meeting.

So there must be something either changing the url ... or redirecting 
your request. You may see more in the inspector of your browser during 
opening the join url.



Thank you, sure ;-)

https://paypal.me/martinthomasschrott




Am 21.01.2021 um 13:35 schrieb jmbarroso84:

**Comment by jmbarroso84** [comment]
Good afternoon Martín,

indeed you are right, there is a redirect.

Status code 302: https://bbb.iberoamericasocial.com/bigbluebutton/api/join?meetingID=1123e354088197bdbd1c7ade52cb5c6330234244%5Cu0026fullName=Live%5Cu0026password=WzuhjGzpNQWO%5Cu0026userdata-bbb_auto_join_audio=true%5Cu0026userdata-bbb_enable_video=true%5Cu0026userdata-bbb_listen_only_mode= true% 5Cu0026userdata-bbb_force_listen_only = true% 5Cu0026userdata-bbb_skip_check_audio = true% 5Cu0026joinViaHtml5 = true% 5Cu0026checksum = 3569c2cab66edbeae56ccd4773e0079af70cbdba% 5Cu0026joinViaHtml5 = true% 5Cu0026checksum = 3569c2cab66edbeae56ccd4773e0079af70cbdba% 5Cu0026


and then it produces error 403: https://bbb.iberoamericasocial.com/?errors=[%7B%22message%22:%22You%20did%20not%20pass%20the%20checksum%20security%20check%22,%22key% 22:% 22checksumError% 22% 7D]


But I have no idea why it does that redirect. I have been searching but have not found a solution to it.

Do you have any idea what might be redirecting? I have verified that the same thing happens with other rooms.

Thank you very much and sorry for so many questions ...

A hug.

**Comment by mtsonline** [comment]
this redirect to the join url may be okay - not sure though.

but what do you get if you open this manually: 
https://bbb.iberoamericasocial.com/bigbluebutton/api

?

Something is not working as expected ...  did you do any changes in the 
live streaming settings?

please try to remove all env configs beside the necessary ones

url, meeting ID and bbb secret.

then try and add the others one by one so we can see where it starts to 
fail.


/

Am 21.01.2021 um 16:51 schrieb jmbarroso84:

**Comment by jmbarroso84** [comment]
Good morning Martín,

I go by steps:

With https://bbb.iberoamericasocial.com/bigbluebutton/api, i get

<response>
<returncode> SUCCESS </returncode>
<version> 2.0 </version>
</response>

I have removed all the livestreaming settings and added them one by one. The result has been as expected.

When testing with docker-compose up, these are the results:

First, without any settings (BBB_URL, BBB_SECRET, BBB_MEETING_ID, BBB_STREAM_URL) it told me that there was no server. Putting BBB_URL = https: //bbb.iberoamericasocial.com/bigbluebutton/api passes the test, but indicates that the secret key is missing.

Second, by putting the secret key, it passes the test, but indicates that the meetingID is missing.

Third, when putting the meetingID, it passes the test (BBB_STREAM_URL is empty) and in the log I have the following results:

{"log": "Starting pulseaudio ... \ n", "stream": "stdout", "time": "2021-01-22T08: 36: 45.757424111Z"}
{"log": "INFO: root: Starting browser !! \ n", "stream": "stdout", "time": "2021-01-22T08: 36: 46.309054345Z"}
livestream exited with code 0

I think this is where the problem comes from. Put what i put in BBB_STREAM_URL, there are problems.

I have tried with:

- rtmp: //a.rtmp.youtube.com/live2/stream/{my youtube stream key}

- rtmp: //a.rtmp.youtube.com/live2/{my youtube stream key}

- And I've even tried only putting an "a" like BBB_STREAM_URL.

The results in all three cases are:

{"log":"INFO:root:https://bbb.iberoamericasocial.com/bigbluebutton/api/join?meetingID=1123e354088197bdbd1c7ade52cb5c6330234244\u0026fullName=Live\u0026password=WzuhjGzpNQWO\u0026userdata-bbb_auto_join_audio=true\u0026userdata-bbb_enable_video=true\u0026userdata-bbb_listen_only_mode=true\u0026userdata-bbb_force_listen_only=true\u0026userdata-bbb_skip_check_audio=true\u0026joinViaHtml5=true\u0026checksum=3569c2cab66edbeae56ccd4773e0079af70cbdba\n","stream":"stdout","time":"2021-01-22T08:41:22.790541286Z"}
{"log":"Traceback (most recent call last):\n","stream":"stdout","time":"2021-01-22T08:41:55.215431054Z"}
{"log":"  File \"stream.py\", line 241, in \u003cmodule\u003e\n","stream":"stdout","time":"2021-01-22T08:41:55.215719064Z"}
{"log":"    bbb_browser()\n","stream":"stdout","time":"2021-01-22T08:41:55.215735464Z"}
{"log":"  File \"stream.py\", line 134, in bbb_browser\n","stream":"stdout","time":"2021-01-22T08:41:55.215744764Z"}
{"log":"    WebDriverWait(browser, selenium_timeout).until(element)\n","stream":"stdout","time":"2021-01-22T08:41:55.215751465Z"}
{"log":"  File \"/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py\", line 80, in until\n","stream":"stdout","time":"2021-01-22T08:41:55.215760165Z"}
{"log":"    raise TimeoutException(message, screen, stacktrace)\n","stream":"stdout","time":"2021-01-22T08:41:55.215768565Z"}
{"log":"selenium.common.exceptions.TimeoutException: Message: \n","stream":"stdout","time":"2021-01-22T08:41:55.215776166Z"}
{"log":"\n","stream":"stdout","time":"2021-01-22T08:41:55.215783466Z"}

The problem, therefore, seems to be in the connection with Youtube, but I don't really understand why. The stream key and the stream url is the same.

Thank you very much Martin. Have a good day!

**Comment by mtsonline** [comment]
Hi,


no the problem is with your bbb - the selenium timeout states, that the 
page does not load as expected.


to see the correct youtube link pattern please searrch the closed 
issues, there where some discussions and the solution, - if you find it, 
feel free to make an pr and add it to the readme or to the examples, - 
if nobody did that already. As we did not use youtube we haven't focused 
on making this easier - sorry.

Still, you will have to get the join url running - when you open this in 
the browser you must see the bbb room - starting with a popup asking for 
audio permissions.
so please just take the join url and try manually to get into the room. 
if this works the selenium error also should disapear. hopefully ;-)


have a great day too


Am 22.01.2021 um 09:48 schrieb jmbarroso84:

**Comment by mtsonline** [comment]
hopefully should work with the current version. cheers
