### ISSUE TITLE
Selenium can't find element

### ISSUE THREAD

**Issue by myOmikron** [aau-zid/BigBlueButton-liveStreaming#103]
Hi,
I'm running this project on a seperate VM (20Cores, 8GB RAM) than my BBB Server. The server is on version 2.2.31.
When starting the project, a live user logs into the conference, but quickly disconnects shortly after that. 
The logs just give a timeout.

When using the DEBUG flag, following error messages appear:
```
liveStreaming   | DEBUG:urllib3.connectionpool:http://127.0.0.1:58917 "POST /session/6a1ba997d570a09a2c0754d1a40aa6e9/url HTTP/1.1" 200 14
liveStreaming   | DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
liveStreaming   | DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:58917/session/6a1ba997d570a09a2c0754d1a40aa6e9/element {"using": "xpath", "value": "//span[contains(@class,\"success\")]"}
```
The last request is retried several times, but every time the error code is 404.

**Comment by myOmikron** [comment]
After commenting the `BBB_ATTENDEE_PASSWORD`, the stream is starting.

**Comment by mtsonline** [comment]
great that you already could solve it yourself.
please always make sure that you use the same passwords as with the application that has created the meetin. e.g. same password as greenlight or moodle used.
You can see the passwords by using the getMeetings tool in the examples folder.
cheers
Martin
