### ISSUE TITLE
XVBF is not always working

### ISSUE THREAD

**Issue by revcjatharv** [aau-zid/BigBlueButton-liveStreaming#105]
Hi All,

If you can support with aws cloudfront as well. And sometime it works fine but sometime its throws and error that xvbf can not run

**Comment by madmax2012** [comment]
I've seen that; it usually happens when you have a broken image / wrong env variables / not enough ressources.

Would you mind sharing your config?

**Comment by mtsonline** [comment]
if there still are issues please try to get more details and reopen this ...
