### ISSUE TITLE
Error while trying to stream live

### ISSUE THREAD

**Issue by odejinmisa** [aau-zid/BigBlueButton-liveStreaming#112]
I am having an issue streaming to youtube and Facebook.

The live user joined the room successfully, I also copied the link and paste into my private browser, I get in successfully and after some minutes it get out of the meeting.

![ls 2021-03-14 213624](https://user-images.githubusercontent.com/62740154/111083368-88230e80-850d-11eb-9ebd-99b6d480c413.png)

Find my docker-compose.yml file below
![lvconfig 2021-03-14 214056](https://user-images.githubusercontent.com/62740154/111083477-2020f800-850e-11eb-8626-6da03ff5f76b.png)
![lvconfig2 2021-03-14 214127](https://user-images.githubusercontent.com/62740154/111083478-21eabb80-850e-11eb-89cb-b436319e5ade.png)

Thanks.

**Comment by clement850** [comment]
Hello, have you resolved this issue ? Thanks

**Comment by odejinmisa** [comment]
I have not. Do you want to help?

**Comment by clement850** [comment]
I would like but I have the same issue...

**Comment by mtsonline** [comment]
Hi, if the user gets removed after some minutes (not seconds) it sounds like a resourse problem of the server. Did you check memory and cpu usage?
If it was a problem with the setup it wouldn't have worked at all or crashed within some seconds.

**Comment by premmohantyagi** [comment]
What the server specification you recommend for this
it's breaking in few seconds on Google Cloud

**Comment by premmohantyagi** [comment]
File "stream.py", line 154, in bbb_browser
liveStreaming   |     element.send_keys("%s : %s" % tmp_chatMsg, tmp_chatUrl)
liveStreaming   | TypeError: not enough arguments for format string

**Comment by mtsonline** [comment]
this hopefully should be fixed with the last merge I just made - there was a bug introduced in the localisation patch last week. Please check if the string problem is solved.
regarding the specs: users reported that 6 cpu cores and 12gb should work - we have no official requirements as we did not make enough tests on that.

**Comment by premmohantyagi** [comment]
@mtsonline  Thanks, it's working on my end now

**Comment by odejinmisa** [comment]
Hi, I am still having the same error on bbb beta1.

It joins the room successfully, but exit after some minutes

Find attached.

![livestreaming](https://user-images.githubusercontent.com/62740154/113838200-750b0380-9786-11eb-9248-16b62b15e33b.png)

**Comment by odejinmisa** [comment]
This is the later part of my docker-compose.yml

Since tit join successfully, i guess there is no need to show the upper part.
 
![livestreaming](https://user-images.githubusercontent.com/62740154/113840611-c3b99d00-9788-11eb-8a4f-b43d6ebb23b9.png)

**Comment by premmohantyagi** [comment]
@odejinmisa Please build you docker again, i think issue will resolve in fresh pull

**Comment by odejinmisa** [comment]
Thanks is working now.
