### ISSUE TITLE
BBB Live Streaming - I setup the live streaming but stuck

### ISSUE THREAD

**Issue by spidernetpln** [aau-zid/BigBlueButton-liveStreaming#14]
Hi Team,

I setup a  BBB Live Streaming you can check here.

Required settings
BBB_URL - URL to BBB including http/https e.g. https://your_BigBlueButton_server/bigbluebutton/api   -----I done this
BBB_MEETING_ID - ID of the BBB Meeting (You can get the ID via an API call: https://your_bbb_server/bigbluebutton/api/getMeetings?checksum=)  -----I don't know how to get it.?
when i tried https://bbb.xyz.com/bigbluebutton/api/getMeetings?checksum=  to copy past on browser it revert me with 

<response>
<returncode>FAILED</returncode>
<messageKey>checksumError</messageKey>
<message>You did not pass the checksum security check</message>
</response>
BBB_SECRET - Secret of your BBB installation (You can get the secret with: bbb-conf --secret) -- -----I done this
BBB_STREAM_URL - Stream URL to your streaming server including rtmp. (e.g. rtmp://media_server_url/stream/stream_key)  -----I don't know how to get streamkey?

root@vmi381532:~/stream# docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS                      NAMES
af1263dfd39e        aauzid/bigbluebutton-livestreaming   "sh docker-entrypoin…"   2 hours ago         Up 2 hours                                     liveStreaming
db27545b7773        xyz:release-v2                   "bin/start"              2 hours ago         Up 2 hours          127.0.0.1:5000->80/tcp     greenlight-v2
3689e7b9758a        postgres:9.5                         "docker-entrypoint.s…"   2 hours ago         Up 2 hours          127.0.0.1:5432->5432/tcp   greenlight_db_1

Please let me know if you need more infromation i installed Greenlight and BBB and it's working fine.

1) how to access stream server after installed.

How to do below setting and where ? which path?

BBB_ENABLE_CHAT - Enable Chat feedback channel
BBB_REDIS_HOST - Set REDIS host (Default: redis)
BBB_REDIS_CHANNEL - Set REDIS channel (Default: chat)
BBB_CHAT_NAME - the username to join the meeting for chatting. (Default: Chat)

**Comment by mtsonline** [comment]
Hi! 


I setup a  BBB Live Streaming you can check here. 


we appreciate that you want to test the streaming. 

BBB_MEETING_ID - ID of the BBB Meeting (You can get the ID via an API call: https://your_bbb_server/bigbluebutton/api/getMeetings?checksum=)  -----I don't know how to get it.? 

please have a look at the bigbluebutton api documentation - there you can see how to get the meeting id. 
We will provide a simpler way to look up the meeting id in a future version, currently we evaluate what would be the best solution here. 

BBB_STREAM_URL - Stream URL to your streaming server including rtmp. (e.g. rtmp://media_server_url/stream/stream_key)  -----I don't know how to get streamkey? 

this depends on your mediaserver, just follow the instructions of your media server documentation or provider and insert the url provided. 


1) how to access stream server after installed. 

the liveStreaming does not include a streamServer - there is nothing to access, it captures the conference and streams it where ever you configure it to. 


How to do below setting and where ? which path? 


the settings are all in the same place, either in the docker-compose.yml or in the .env file, see the examples. 

hth 
Martin
