### ISSUE TITLE
Error 137

### ISSUE THREAD

**Issue by ffarenea** [aau-zid/BigBlueButton-liveStreaming#144]
Hello,

I am trying to use bigbluebutton-livestreaming 1.0.0-beta.8 with bigbluebutton 2.4-rc7.

After a successful connection by the Live user, an RTMP stream that goes up well and a few seconds, I got this error:
 _**exited with code 137   29900kB time=00:00:58.72 bitrate=4170.9kbits/s dup=0 drop=3 speed=0.983x     0x**_

This version of livestreaming run with a "local" docker and work fine with bigbluebutton 2.3.

**Comment by mtsonline** [comment]
thank you for reporting this.
will be fixed with #145

**Comment by ffarenea** [comment]
Thank you, but the mistake has happened again:
 exited with code 137   24632kB time=00:00:49.05 bitrate=4113.1kbits/s dup=0 drop=3 speed=0.98x      0x
