### ISSUE TITLE
BBB 2.4-rc7: Change needed to be able to run

### ISSUE THREAD

**Issue by PhMemmel** [aau-zid/BigBlueButton-liveStreaming#145]
Due to changes in the latest BBB HTML5 client we need to adapt something here:

https://github.com/aau-zid/BigBlueButton-liveStreaming/blob/58ef7941e46e506d37f6d678e949412cc1aa96eb/stream.py#L161

We need to change `User list` to `Users list` here and everything runs fine again when building a docker image with this custom change.

**Comment by mtsonline** [comment]
thanks Pypo, would you provide the change as PR?
cheers

**Comment by PhMemmel** [comment]
Wasn't sure about if we have separate branches for backwards compatibility to 2.3 or sth, but if not - I can provide PR for master soon, sure

**Comment by mtsonline** [comment]
may you have a look at one of the last prs - there was an example with an if, that allowed for backwardscompatibility. ;-)
Hope this should work for this one too, so we can keep one version for 2.3 and 2.4 versions.

**Comment by PhMemmel** [comment]
Alright :-)
