### ISSUE TITLE
BBB can't live streaming to Facebook Live

### ISSUE THREAD

**Issue by newparadise2020** [aau-zid/BigBlueButton-liveStreaming#15]
Hi folks, I have problems with the docker...
my current config:
    environment:
      # BigBlueButton Server url:
      - BBB_URL=https://bbb.xxxxxx.com/bigbluebutton/
      # BigBlueButton secret:
      - BBB_SECRET=therightsecretishere
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=rightIDobtainedfromBBB
      # Media server url:
      - BBB_STREAM_URL=rtmps://live-api-s.facebook.com:443/rtmp/myrightFBstreamkey

Start BBB meeting successfully, with 2 users connected ok watching & listening
Started docker liveStreaming successfully, but stream never reaches FB Live
Checking docker liveStreaming logs... message is:
"INFO:root:Meeting isn't running. We will try again in 5 seconds!"
Why docker cant see meeting running?
Do I need to do something else?

Thanks!!!

**Comment by mtsonline** [comment]
> my current config:
> environment:
> # BigBlueButton Server url:
> - BBB_URL=https://bbb.xxxxxx.com/bigbluebutton/
>

if the url above is correct, this may be the problem. The example states:


       # BigBlueButton Server url:
       - BBB_URL=https://your_BigBlueButton_server/bigbluebutton/api


you missed out the /api part.


hth

Martin

**Comment by newparadise2020** [comment]
> # BigBlueButton Server url:       - BBB_URL=https://your_BigBlueButton_server/bigbluebutton/api
I fixed this, and semms to docker starts ok, but logs tell me this now:

ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[x11grab @ 0x5589d9041dc0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':122':
  Duration: N/A, start: 1589217494.814776, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 29.97 fps, 1000k tbr, 1000k tbn, 1000k tbc
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, alsa, from 'pulse':
  Duration: N/A, start: 1589217494.895818, bitrate: 1536 kb/s
    Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
[rtmps @ 0x5589d90765c0] Cannot open connection tls://live-api-s.facebook.com:443
rtmps://live-api-s.facebook.com:443/rtmp/MYSTREAMKEYHERE: Resource temporarily unavailable

any ideas?

**Comment by newparadise2020** [comment]
Updated: Test  same docker's ffmpeg to stream another video to FB live... successfully!
(then it's not ffmpeg trouble)

But when stream the BBB meeting can't solve this issue. Process started ok, connected "Live" user to the room, but can't stream

> [x11grab @ 0x5589d9041dc0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':122':
Duration: N/A, start: 1589217494.814776, bitrate: N/A
Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 29.97 fps, 1000k tbr, 1000k tbn, 1000k tbc
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, alsa, from 'pulse':
Duration: N/A, start: 1589217494.895818, bitrate: 1536 kb/s
Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
[rtmps @ 0x5589d90765c0] Cannot open connection tls://live-api-s.facebook.com:443
rtmps://live-api-s.facebook.com:443/rtmp/MYSTREAMKEYHERE: Resource temporarily unavailable

**Comment by pbdco** [comment]
hi @newparadise2020 could you please explain how did you get FB streaming to work? If its too much work to write down the steps, could you please share a video jsut showing your proceedement? This will be increibly helpful for me and others thousands of people trying to get it to work (for the lack of documentation of this procedure) 

I will be very thankful in advance, regard.

**Comment by newparadise2020** [comment]
> hi @newparadise2020 could you please explain how did you get FB streaming to work? If its too much work to write down the steps, could you please share a video jsut showing your proceedement? This will be increibly helpful for me and others thousands of people trying to get it to work (for the lack of documentation of this procedure)

In fact BBB streaming to FB Live can't work for me!

My test only was: Run ffmpeg compiled with ssl support, and stream any video for test to rmtps FB live address (and key) was successfully. This guide help me:  [http://www.iiwnz.com/compile-ffmpeg-with-rtmps-for-facebook/](url)

But can't yet stream a BBB meeting to FB live using this liveStreaming docker( I think that is what we are interested in achieving here)

**Comment by PasqualeAiello** [comment]
I think that you are encoding flv standard so you can't arrive at less 4500 bitrate of H264

**Comment by mtsonline** [comment]
@newparadise2020 could you provide us with your ffmpeg command that worked with facebook?

thanks everybody for testing and all your feedback.

**Comment by newparadise2020** [comment]
> @newparadise2020 could you provide us with your ffmpeg command that worked with facebook?
> 
> thanks everybody for testing and all your feedback.

/ffmpeg -f lavfi -re -i "life=s=300x200:mold=10:r=25:ratio=0.1:death_color=#C83232:life_color=#00ff00,scale=1200:800:flags=16" -f lavfi -re -i sine=frequency=1000:sample_rate=44100 -pix_fmt yuv420p -c:v libx264 -b:v 1000k -g 30 -keyint_min 120 -profile:v baseline -preset veryfast -c:a aac -b:a 96k  -f flv "rtmps://live-api-s.facebook.com:443/rtmp/{YOUR STREAM KEY}"

It's only  a video test but works...

**Comment by mikosche** [comment]
@newparadise2020 we fixed the Facebook problem, now you should be able to stream

Thanks for the feedback
