### ISSUE TITLE
Cannot read property 'setAttribute' of null

### ISSUE THREAD

**Issue by cod3r0k** [aau-zid/BigBlueButton-liveStreaming#151]
f8f
INFO:root:Waiting for chat input window to appear.
INFO:root:could not find chat input or chat toggle
[]
Traceback (most recent call last):
  File "stream.py", line 270, in <module>
    bbb_browser()
  File "stream.py", line 197, in bbb_browser
    browser.execute_script("document.getElementById('container').setAttribute('style','margin-bottom:30px');")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'setAttribute' of null
  (Session info: chrome=91.0.4472.77)

**Comment by fl4t23** [comment]
same problem.
this has already been fixed and merged [ BBB 2.4 #139 ](https://github.com/aau-zid/BigBlueButton-liveStreaming/issues/139), but it might not build the right docker image, if you do per docker-compose.yml.
a quick fix is, if you clone the repo and then start by docker-compose.yml.development and the image is built by local with the fixed stream.py

**Comment by mtsonline** [comment]
we will release a new version next week or the week after with the merged changes so you won't longer have to check out the repo. In the meantime this is an easy workarround ;-)
We want to wait if more bugs are discovered with 2.4 or the new fixes so the next release will work stable. Thanks

**Comment by ddeenniiss** [comment]
same error here

```
liveStreaming   | Traceback (most recent call last):
liveStreaming   |   File "stream.py", line 262, in <module>
liveStreaming   |     bbb_browser()
liveStreaming   |   File "stream.py", line 190, in bbb_browser
liveStreaming   |     browser.execute_script("document.getElementById('container').setAttribute('style','margin-bottom:30px');")
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
liveStreaming   |     'args': converted_args})['value']
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
liveStreaming   |     self.error_handler.check_response(response)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
liveStreaming   |     raise exception_class(message, screen, stacktrace)
liveStreaming   | selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'setAttribute' of null
liveStreaming   |   (Session info: chrome=91.0.4472.77)

```

**Comment by mtsonline** [comment]
should already be fixed - please check, that you use the current version.

**Comment by ddeenniiss** [comment]
yes, it's the current

**Comment by mtsonline** [comment]
do you think it is the current, or did you actually compare the files with the master branch?
As there was reported, that this has been fixed already, this may be something different / or your version was not updated yet?
Do you have the same problem, when you checkout the git master branch and start with the mentioned local build?
