### ISSUE TITLE
Not seeing Youtube viewer chats in BBB meeting

### ISSUE THREAD

**Issue by beri-sela** [aau-zid/BigBlueButton-liveStreaming#16]
Thanks for this great solution. I have implemented and it works well. However, I don't see the chats from youtube viewers. The default chat message is sent and the Chat user is present in the meeting, but nothing afterwards. Has anyone been able to see the chats in the meeting room? Thanks.

**Comment by PasqualeAiello** [comment]
I loose Chat User too after few second.
A question what bitrate do you have on youtube ?

**Comment by mikosche** [comment]
Hi @beri-sela 
The idea of the chat was that you can send messages over Redis to BBB, there is a docker-compose example under examples and i will add a PHP Script to send messages as an example.
There is no support to for YouTube chats and comments.

cheers

**Comment by beri-sela** [comment]
> Hi @beri-sela
> The idea of the chat was that you can send messages over Redis to BBB, there is a docker-compose example under examples and i will a PHP Script to send messages as an example.
> There is no support to for YouTube chats and comments.
> 
> cheers

I understand now. 
Thank you.

**Comment by beri-sela** [comment]
> I loose Chat User too after few second.
> A question what bitrate do you have on youtube ?

If you have toggled your chat and users list by default, you will have that problem. You will need to edit the chat.py file. 
For bitrate, I got 581.46 Kbps on average.
