### ISSUE TITLE
 File "./get_meetings.py", line 5, in <module>     from bigbluebutton_api_python import BigBlueButton ImportError: No module named 'bigbluebutton_api_python'

### ISSUE THREAD

**Issue by zihniartar** [aau-zid/BigBlueButton-liveStreaming#22]
Hi,

i get the following error:

 File "./get_meetings.py", line 5, in <module>
    from bigbluebutton_api_python import BigBlueButton
ImportError: No module named 'bigbluebutton_api_python'

I have installed https://github.com/yunkaiwang/bigbluebutton-api-python.

**Comment by mtsonline** [comment]
Hi,


how did you install the module?

pip3 install <module name>

should solve this.

**Comment by zihniartar** [comment]
i get this message after running  pip install bigbluebutton_api_python

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: bigbluebutton_api_python in /usr/local/lib/python2.7/dist-packages (0.0.11)
Requirement already satisfied: jxmlease in /usr/local/lib/python2.7/dist-packages (from bigbluebutton_api_python) (1.0.1)


my python version is 3.5.2.

**Comment by mtsonline** [comment]
Hi,


as I wrote, please use:

pip3 install

otherwise you won't install the module for python3..

You installed it for python2 - the getMeetings script is written in python3.


hth

Martin

**Comment by zihniartar** [comment]
Thanks, that worked.

Another question: Can I stream to youtube with it now?

Youtube requires a key and the server URL.

Where can I enter the key?

**Comment by zihniartar** [comment]
ok, i figured it out:

 - BBB_STREAM_URL={youtube-server-url} + / + {Name/Key}
