### ISSUE TITLE
get_meetings.py: more than 1 running meeting

### ISSUE THREAD

**Issue by zihniartar** [aau-zid/BigBlueButton-liveStreaming#23]
if more than one meeting is currently running, the following error message appears:

Traceback (most recent call last):
  File "./get_meetings.py", line 46, in <module>
    print(meetings['xml']['meetings'][meeting]['meetingName'])
TypeError: list indices must be integers or slices, not str

But if only one meeting is running, there is no problem

**Comment by mtsonline** [comment]
thank you for this report.

Will be fixed in the next beta.

cheers

Martin
