### ISSUE TITLE
The live streaming to youtube is done very well, however it consumes more than 100% of the CPU.

### ISSUE THREAD

**Issue by iwebsur** [aau-zid/BigBlueButton-liveStreaming#27]
**Describe the bug**
The transmission to youtube is done very well, however it consumes more than 100% of the CPU.

**To Reproduce**
1. I configure according to the documentation -> OK
2. There is no camera, only the default.pdf slide
2. I make the live transmission to youtube -> OK
3. On the command line I type $ top
4. Result % CPU more than 100%

**Expected behavior**
The consumption should not be so high if there is only the slide.

**Screenshots**
![Captura de Pantalla 2020-05-20 a la(s) 1 52 05 a  m](https://user-images.githubusercontent.com/64039653/82482323-4fa4d680-9a9c-11ea-98ce-ae88d9828472.png)

Thank you for your time in contributing to this wonderful complement to BigBlueButton.

**Comment by mtsonline** [comment]
thanks for your words! :-) nice to make people happy with this tool.


we are evaluating, where we can improve the cpu usage, but mainly ffmpeg 
causes the load beside the browser that captures the meeting.

Have you chat enabled? This doubles the cpu load of the browser part.

We are working on reducing at least this.


Maybe lowering the quality could decrease cpu usage of ffmpeg, we did 
not try this for now, but we will make the quality more flexible.


what type of server are you using / vm / bare metal / cores ...


cheers

Martin

**Comment by iwebsur** [comment]
I am testing on a dedicated server with features that exceed the minimum server requirements for BigBlueButton:
Intel Xeon-E 2136 - 6c/ 12t - 3.3GHz/ 4.5GHz
64GB DDR4 ECC 2666 MHz

Therefore, the expected result is that it does not consume as many CPU resources.

I think the path is correct, so I recommend that you continue to develop this plugin which will surely help many who use BigBlueButton around the world. Thank you.

**Comment by mtsonline** [comment]
Hi, 
6 cores defenitely will not be enough for bbb and the streamer. We tested the streamer on a separate server and it required 8 cores to run stable.
we still are evaluating what would be the real minimum requirements and will post this in the readme, when we have a valid result.

Try it on a separate server or with more cores and tell us your results please.
cheers
