### ISSUE TITLE
Combine with GreenLight Docker

### ISSUE THREAD

**Issue by rezaervani** [aau-zid/BigBlueButton-liveStreaming#28]
**Is your feature request related to a problem? Please describe.**
How to combine this docker with GreenLight Docker

**Describe the solution you'd like**
We use greenlight for our BBB Server 2.9.11. It also use docker. How to combine docker-compose.yml between greenlight and BBB-liveStreaming

Thank you,

**Comment by mtsonline** [comment]
Hi,

you do not have to combine these two docker containers.

Just make different folders for the docker containers - in each folder 
you can have a docker-compose file.


Please make sure, that you have enough cpu power available on your 
server, if you run everything on one host.


cheers

Martin
