### ISSUE TITLE
Live stream screen setup

### ISSUE THREAD

**Issue by penguennoktanet** [aau-zid/BigBlueButton-liveStreaming#29]
Hi team,

I just want to ask a simple question, but I can not find an FAQ or mailling list. So decided to ask here.

I am going to use liveStreaming to stream some meetings to youtube. But I want to resize/hide the presentation section, focus some videos on the go.. It is possible or a trick that I can use?

Thanks for your efforts.

**Comment by mtsonline** [comment]
unfortunately not really. To change things you always will have to use selenium to simulate clicks on the screen, as there is no api available in the htmlclient and no api call in bbb to set the style.
it is on our todolist to have a look at the api and how it could be extended, but it would be very helpful if more people could help to improove. :-)
if the api of bbb would allow to set styles and switch between the audio/non audio modes/turn off cameras and so on, we could remove selenium and be much more efficient and flexible.

**Comment by abhas** [comment]
> But I want to resize/hide the presentation section, focus some videos on the go.. It is possible or a trick that I can use?

https://github.com/abhas/BigBlueButton-liveStreaming/commit/abd003743889e4c779d4b98f1c5c90e7fdafd8fa

This is a quick two-line hack to hide the presentation in the live-stream

**Comment by mtsonline** [comment]
Thanks Abhas,
if you add an if and a environment variable for hiding the presentation  and push a pull request, we could made it available as new option.

we plan to make more things optional, so any work on such settings is appreciated.
cheers

**Comment by abhas** [comment]
> if you add an if and a environment variable for hiding the presentation and push a pull request, we could made it available as new option.

Yes - I'll do that shortly and send you a pull request.

**Comment by mtsonline** [comment]
we changed the join url so you could use userdata parameters to hide the presentation or even submit a custom css ...
have a look at the get_join_url function in the python files ...

if you still are interested we will be happy to merge your pull request if you add some options for css style or hiding elements via parameters in the docker-compose ...

**Comment by mtsonline** [comment]
@abhas we merged some pull requests that added ffmpeg options. Would still be great if you could add the customisation parameters / presentation variables and functionality ;-)

cheers

**Comment by mtsonline** [comment]
I will close this. still hope someone adds the features via a pull request... thanks
