### ISSUE TITLE
Meeting isn't running. We will try again in 5 seconds!

### ISSUE THREAD

**Issue by shah-manthan9** [aau-zid/BigBlueButton-liveStreaming#3]
Hi, 
Every time it shows
INFO:root:Meeting isn't running. We will try again in 5 seconds!

can you please help!!!

**Comment by shah-manthan9** [comment]
I understood how to get the meeting id

**Comment by mtsonline** [comment]
Hi,

the meeting has to be started. Unless you do this, the streamer cannot 
join the meeting.

Would not make sense to stream unless there is someone in the room 
though. :-)


hth

Martin

**Comment by zihniartar** [comment]
> I understood how to get the meeting id

How did you get die meeting id?

**Comment by mtsonline** [comment]
have a look at the example folder, we added a new script get_meetings which shows you all IDs of the meetings that currently are running on the configured server.
