### ISSUE TITLE
Nginx rtmp to HLS or dash - audio works, video not

### ISSUE THREAD

**Issue by timm2k** [aau-zid/BigBlueButton-liveStreaming#31]
Hi there,

first of all thanks for your great work on streaming BBB sessions!

I'd like to use nginx with rtmp stream support to stream BBB sessions via liveStreaming to a webpage with video.js eg.

The architecture is quite simple and straight forward:
- Start a BBB session
- connect BBB-liveStreaming and stream to nginx
- let nginx rtmp module create HLS or dash output
- point a webpage with video.js + HLS support to HLS stream of nginx

There is a nice video and documentation at https://www.nginx.com/blog/video-streaming-for-remote-learning-with-nginx/ for nginx+rtmp with HLS and dash output.

Connecting with VLC to nginx rtmp stream is no problem and works as expected.
Connecting with VLC to nginx HLS or dash output gives only audio of the BBB session.

I suppose the video output parameters of BBB-liveStreaming are not compatible with HLS or dash.
I've currently no evidence for my thesis but streaming an mp4 movie works as expected via HLS or dash.

Is there any way how I can change ffmpeg parameters of docker container on my own?
Other suggestions are welcome as well!

Kind regards
Timm

**Comment by mikosche** [comment]
Hi @timm2k 

thanks for your feedback.

We are also using nginx+rtmp module and it works just fine.
I will give you an example of our nginx.conf

```
rtmp {
    server {
    
        application stream {
            live on;

            exec ffmpeg -i rtmp://localhost/stream/$name
              -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 1000k -f flv -g 30 -r 30 -s 854x480 -preset superfast -profile:v baseline rtmp://localhost/hls/$name_480p;
             # -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 2500k -f flv -g 30 -r 30 -s 1280x720 -preset superfast -profile:v baseline rtmp://localhost/hls/$name_720p25
             # -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 750k -f flv -g 30 -r 30 -s 640x360 -preset superfast -profile:v baseline rtmp://localhost/hls/$name_360p7
             # -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 400k -f flv -g 30 -r 30 -s 426x240 -preset superfast -profile:v baseline rtmp://localhost/hls/$name_240p4
             # -c:a libfdk_aac -b:a 64k -c:v libx264 -b:v 200k -f flv -g 15 -r 15 -s 426x240 -preset superfast -profile:v baseline rtmp://localhost/hls/$name_240p2;
              
            allow play 127.0.0.1;
            deny play all;
        }

        application hls {
            live on;
            hls on;
            hls_fragment_naming system;
            hls_fragment 5;
            hls_playlist_length 10;
            hls_path /PATH/TO/HLS/DATA;
            hls_nested on;

            #hls_variant _720p25 BANDWIDTH=2628000,RESOLUTION=1280x720;
            hls_variant _480p10 BANDWIDTH=1128000,RESOLUTION=854x480;
            #hls_variant _360p7 BANDWIDTH=878000,RESOLUTION=640x360;
            #hls_variant _240p4 BANDWIDTH=528000,RESOLUTION=426x240;
            #hls_variant _240p2 BANDWIDTH=264000,RESOLUTION=426x240;
            
            deny play all;
            allow publish 127.0.0.1;
            deny publish all;
        }
    }
}

http{
      server{

 location /live {
          alias /live;
          types {
              application/vnd.apple.mpegurl m3u8;
              video/mp2t ts;
          }
          add_header Cache-Control no-cache;
          add_header Access-Control-Allow-Origin *;
        }
}
}
```
I hope this will help you.

We also currently working on custom parameters for ffmpeg.

Kind regards
Michael

**Comment by mikosche** [comment]
Hi @timm2k 

We created a NGINX+RTMP Live Streaming Server https://github.com/aau-zid/live-streaming-server
Currently only HLS is supported, we will improve it for DASH later.

At the development i also has a problem that only audio but no video was streamed. In my case i run out of memory, so nginx don't worked correct.

Kind regards
Michael

**Comment by looped-monk** [comment]
@mikosche Just a question, for live audio instead of live video, any tutorial on how to to go about it?  I believe i wouldnt need to use ffmpeg for any conversion on nginx from video to audio since the the video consumption can be disabled from the front end app ? Further to that, on the http end of my nginx my live audio looks similar to live video:

`location /live/hls-live-audio {
                expires max;
                types {
                    application/vnd.apple.mpegurl m3u8;
                    video/mp2t ts;
                    }
                    root /opt/data;
                    add_header Cache-Control no-cache;
                    add_header Access-Control-Allow-Origin *;
            }`
Does 
`video/mp2t ts 
`need to be changed to 
`audio/mp2t ts ` for live audio ?
