### ISSUE TITLE
Install livestreaming

### ISSUE THREAD

**Issue by premryp** [aau-zid/BigBlueButton-liveStreaming#35]
Hello whether I need to install the livestreaming in bbb server itself, or separate one. 

Shall I use Ant Media server and youtube for streaming

**Comment by mtsonline** [comment]
it depends on your BBB Server. If you have enough cpu and memory you can 
install the liveStreaming on the same server - but installing on its own 
server should be prefered.


You can use either media target - any media server will be fine and 
youtube or other platforms should work well.


cheers

**Comment by premryp** [comment]
Thanks for your information.

How can I dynamic pass RTMP url using API
eg: You have different youtube channel and I have different youtube channel.

**Comment by mtsonline** [comment]
currently there is no api to configure or start the streaming

But you can remotely start the streamer e.g. via the shell:

ssh root@$1 "cd; cd BigBlueButton-liveStreaming; BBB_MEETING_ID=\"$2\" 
BBB_STREAM_URL=\"$3\" BBB_INTRO=\"\" docker-compose up -d"


the parameters you give via the shell may not be configured in the 
docker-compose.yml file though.

cheers
