### ISSUE TITLE
turn off chat message with stream ID

### ISSUE THREAD

**Issue by drlight17** [aau-zid/BigBlueButton-liveStreaming#36]
Hi. For now when streaming starts bot sends a chat message with the full link to RTMP server with stream ID (Message is like "This meeting is streamed to: rtmp://..."). Is there an option to not let streaming bot to send this message?

**Comment by mtsonline** [comment]
Hi,


thanks for your feedback - it is already on our todo to remove the full 
URL from the message.


cheers

Martin

**Comment by drlight17** [comment]
> Hi, thanks for your feedback - it is already on our todo to remove the full URL from the message. cheers Martin

Nice, thanks! Will wait for it.

**Comment by donpeek** [comment]
If you wanted to you could mark out line 80 of the stream.py with a # and that should help with a quick fix for now...

**Comment by fkohrt** [comment]
> it is already on our todo to remove the full URL from the message.

@mtsonline I like the idea that participants are aware that the event is live streamed, but maybe it's more helpful to inform where participants can watch the live stream. Because this location is non-generic, maybe introduce another variable that's sets this viewer URL?
