### ISSUE TITLE
Strange errors

### ISSUE THREAD

**Issue by donpeek** [aau-zid/BigBlueButton-liveStreaming#37]
[aac @ 0x55fb5b270780] Queue input is backward in time
liveStreaming   | frame= 6429 fps= 13 q=0.0 size=  105561kB time=00:06:45.60 bitrate=2132.0kbits/s d[flv @ 0x55fb5b26a680] Non-monotonous DTS in output stream 0:1; previous: 405587, current: 405569; changing to 405587. This may result in incorrect timestamps in the output file.
[aac @ 0x55fb5b270780] Queue input is backward in time2.53 bitrate=2110.5kbits/s dup=0 drop=5 speed=0.836x    5 speed=0.829x
liveStreaming   |     Last message repeated 2 times

I don't know what this is about ?  Help ? 
It just a basic setup... I could post it but nothing in it says turn this on to make time flow backwards :-) 
Thanks
Don

**Comment by donpeek** [comment]
version: '3.3'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    environment:



    # BigBlueButton Server url:
      - BBB_URL=https://sys1.vics-server.com/bigbluebutton/api
      # BigBlueButton secret:
      - BBB_SECRET=REMOVED
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=21c19753a984c68837d5286f6a7300e342948e4f
      # start meeting (optional):
      - BBB_START_MEETING=false
      # attendee password (optional - has to be set to the attendee password of moodle/greenlight
 any other frontend to allow joining via their links):
      - BBB_ATTENDEE_PASSWORD=RmloKslXurHh
      # moderator password (optional - has to be set to the moderator password of moodle/greenlig
or any other frontend to allow joining via their links):
      - BBB_MODERATOR_PASSWORD=cWmBhiFPUjfn
      # meeting title (optional):
      - BBB_MEETING_TITLE=live
      # download / save BigBlueButton meeting
      - BBB_DOWNLOAD_MEETING=false
      # begin the intro at position (optional, e.g. 00:00:05)
      - BBB_BEGIN_INTRO_AT=00:00:00
      # end intro after (optional, e.g. 01:00:00 - after one hour)
      - BBB_END_INTRO_AT=00:00:00
      # play intro file (can be a local file in videodata folder e.g. /video/intro.mp4 or a url omediastream e.g. https://my.intro.stream)
      - BBB_INTRO
    # Media server url:
     #   - BBB_STREAM_URL=rtmp://media_server_url/stream/stream_key
      - BBB_STREAM_URL=rtmp://thedemozone.com/live/
      # Timezone (default: Europe/Vienna):
      - TZ=Europe/Vienna

    volumes:
      - ./videodata:/video

**Comment by mtsonline** [comment]
do you still have this issue? ...anything new on it?

**Comment by SadeqRouhani** [comment]
Hi every body

I have same problem, please help me.
It just basic setup with default parametera.

I thought the cause was time zone. But it did not any diffrent with change timezone

Help please

**Comment by mtsonline** [comment]
please give more details on your problem.
