### ISSUE TITLE
streaming isnt staring

### ISSUE THREAD

**Issue by kaneki666** [aau-zid/BigBlueButton-liveStreaming#38]
i have followed your documentation and edited this file it starts without error but Facebook stream blank
my docker-compose.yml
version: '2.0'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    environment:
      # BigBlueButton Server url:
      - BBB_URL=http://34.87.179.205/bigbluebutton/api
      # BigBlueButton secret:
      - BBB_SECRET=wuEWZryH81zNvLYjphgoo0lw4rBrYFZg1NI8Hj1Dw
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1594299922525
      # download / save BigBlueButton meeting
      - BBB_DOWNLOAD_MEETING=false
      # play intro file (can be a local file in videodata folder e.g. /video/intro.mp4 or a url of a mediastream e.g. https://my.intro.stream)
      - BBB_INTRO=false
      # begin the intro at position (optional, e.g. 00:00:05)
      - BBB_BEGIN_INTRO_AT=04:40
      # end intro after (optional, e.g. 01:00:00 - after one hour)
      - BBB_END_INTRO_AT=
      # Media server url:
      - BBB_STREAM_URL=rtmps://live-api-s.facebook.com:443/rtmp/3191579940864754?s_bl=1&s_sc=3191579977531417&s_sw=0&s_vt=api-s&a=AbxBnEzznPHo66En
      # Timezone (default: Europe/Vienna):
      - TZ=Europe/Vienna

    volumes:
      - ./videodata:/video

i have started steaming by following this..ik its not an issue with code..anyone can help me out? thanks in advance
wget -O docker-compose.yml https://raw.github.com/aau-zid/BigBlueButton-liveStreaming/1.0.0-beta.5/examples/docker-compose.yml.example
(change configuration)
docker-compose up -d

**Comment by mtsonline** [comment]
not sure if this may be related, but your bbb url is not https ... I 
could imagine that this makes problems, but have not tested that at all.

do you get any errors?

**Comment by kaneki666** [comment]
ok i will try https...but dont think its the prb..no i dont get any error..its says streaming started but nothing...is my yml my wrong? do i have to do anything else to start streaming i just follow then documention.

**Comment by kaneki666** [comment]
[](url)
