### ISSUE TITLE
Instructions to use the chat feature are missing

### ISSUE THREAD

**Issue by dakser** [aau-zid/BigBlueButton-liveStreaming#39]
Hi, I can see the examples folder player_and_chat.php and sendChatMessage.php but I can't find any instructions to use this feature, and it's very important to let viewers interact to the participants in the BBB meeting room that are making the livestreaming. Any help is appreciated.
Best regards.

**Comment by mtsonline** [comment]
Hi,


just place the php file on a webhost. make sure the redis port can be 
reached from there.

have a look at the code of the file, it is kept simple to better 
understand it.

and do not forget to enable the chat feedback in the docker-compose file.


cheers

Martin

**Comment by kaneki666** [comment]
in which folder i have to add the php file ? i dont know much about redis

**Comment by mtsonline** [comment]
it won't matter where you place the php file - just make sure the php file with the html form can call the other php file that processes the data 
and the php file that is processing can reach the configured redis port.
redis is just like any other database.
hth

**Comment by mtsonline** [comment]
added in the next version
