### ISSUE TITLE
Can u tell me whole process to start streaming?

### ISSUE THREAD

**Issue by kaneki666** [aau-zid/BigBlueButton-liveStreaming#42]
i followed the documentation...first downloaded the yml file.. i have put my variables there then run docker-compose up -d.. then some pacakage  downloads and it says Creating liveStreaming and starting no error but stream blank..hel

**Comment by mtsonline** [comment]
where do you see a blank page? 
to which media server are you streaming?
what is the output of the logs?

**Comment by kaneki666** [comment]
I see blank page where supposed to be stream come..i am trying to host in Facebook live..
![IMG-20200709-WA0006](https://user-images.githubusercontent.com/41444793/87223861-38021400-c3a2-11ea-935b-de35d737df65.jpeg)
I am google cloud console as server...i have a running bbb server...i am using both different server..how to see the logs?... If you don't mind can you make a small video of whole process?!

This is my yml file
https://github.com/kaneki666/BigBlueButton-liveStreaming/blob/master/examples/docker-compose.yml.example

**Comment by mtsonline** [comment]
have a look at 
#43
maybe mbile can help you to get it to run :-)
