### ISSUE TITLE
I can't start a livestream on either facebook page/group or youtube channel

### ISSUE THREAD

**Issue by mbile** [aau-zid/BigBlueButton-liveStreaming#43]
Hello BigBlueButton-liveStreaming team,

Thanks for this great project. I have followed all the steps you've mentioned in the readme page on Github. I am stuck getting the BBB_STREAM_URL value. Is BBB_STREAM_URL my Facebook page/youtube channel I am going to stream the meeting to?

I have tried to stream a meeting on a Facebook page, it gave me Stream URL and Stream key but I couldn't find a way to put the stream key into the docker-compose.yml file. To test it, I put the stream URL into the file but got this error:

liveStreaming   |   libavutil      56. 51.100 / 56. 51.100
liveStreaming   |   libavcodec     58. 91.100 / 58. 91.100
liveStreaming   |   libavformat    58. 45.100 / 58. 45.100
liveStreaming   |   libavdevice    58. 10.100 / 58. 10.100
liveStreaming   |   libavfilter     7. 85.100 /  7. 85.100
liveStreaming   |   libavresample   4.  0.  0 /  4.  0.  0
liveStreaming   |   libswscale      5.  7.100 /  5.  7.100
liveStreaming   |   libswresample   3.  7.100 /  3.  7.100
liveStreaming   |   libpostproc    55.  7.100 / 55.  7.100
liveStreaming   | [x11grab @ 0x5587fdc13200] Stream #0: not enough frames to estimate rate; consider increasing probesize
liveStreaming   | Input #0, x11grab, from ':122':
liveStreaming   |   Duration: N/A, start: 1594463332.353569, bitrate: 1988667 kb/s
liveStreaming   |     Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 1988667 kb/s, 29.97 fps, 1000k tbr, 1000k tbn, 1000k tbc
liveStreaming   | [x11grab @ 0x56087da2a6c0] Stream #0: not enough frames to estimate rate; consider increasing probesize
liveStreaming   | Input #0, x11grab, from ':122':
liveStreaming   |   Duration: N/A, start: 1594463332.365846, bitrate: 1988667 kb/s
liveStreaming   |     Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 1988667 kb/s, 29.97 fps, 1000k tbr, 1000k tbn, 1000k tbc
liveStreaming   | ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
liveStreaming   | 
liveStreaming   | [alsa @ 0x56087da35180] cannot open audio device pulse (Connection refused)
liveStreaming   | pulse: Input/output error
liveStreaming   | ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
liveStreaming   | 
liveStreaming   | [alsa @ 0x5587fdc1de00] cannot open audio device pulse (Connection refused)
liveStreaming   | pulse: Input/output error
liveStreaming exited with code 0

Thanks in advance.

**Comment by mtsonline** [comment]
Hi,

yes, it is the rtmp url you get from your media server provider or the url to your media server.
You find this when you checkout how to stream via facebook or youtube. In youtube you use youtube studio for it.
cheers
Martin

**Comment by mtsonline** [comment]
here is the guide from google for youtube:
https://support.google.com/youtube/answer/2907883

**Comment by mbile** [comment]
Hello @mtsonline,

Thanks for the reply. followed the link you've given me. it says "To start streaming, enter your YouTube Live server URL and stream key into your encoder". How can pass the stream key into the docker-compose.yml file? I have just passed the URL and this is the log:

liveStreaming is up-to-date
Attaching to liveStreaming
liveStreaming   | INFO:root:Starting browser!!
liveStreaming   | INFO:root:streaming intro...
liveStreaming   | ffmpeg version 4.3-2~18.04.york0 Copyright (c) 2000-2020 the FFmpeg developers
liveStreaming   |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
liveStreaming   |   configuration: --prefix=/usr --extra-version='2~18.04.york0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
liveStreaming   |   libavutil      56. 51.100 / 56. 51.100
liveStreaming   |   libavcodec     58. 91.100 / 58. 91.100
liveStreaming   |   libavformat    58. 45.100 / 58. 45.100
liveStreaming   |   libavdevice    58. 10.100 / 58. 10.100
liveStreaming   |   libavfilter     7. 85.100 /  7. 85.100
liveStreaming   |   libavresample   4.  0.  0 /  4.  0.  0
liveStreaming   |   libswscale      5.  7.100 /  5.  7.100
liveStreaming   |   libswresample   3.  7.100 /  3.  7.100
liveStreaming   |   libpostproc    55.  7.100 / 55.  7.100
liveStreaming   | false: No such file or directory
liveStreaming   | INFO:root:Open BBB and hide elements!!
liveStreaming   | INFO:root:create_meeting...
liveStreaming   | INFO:root:get_join_url...
liveStreaming   | INFO:root:saving meeting as /video/meeting-20200711135428.mkv
liveStreaming   | INFO:root:streaming meeting...
liveStreaming   | ffmpeg version 4.3-2~18.04.york0 Copyright (c) 2000-2020 the FFmpeg developers
liveStreaming   |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
liveStreaming   |   configuration: --prefix=/usr --extra-version='2~18.04.york0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
liveStreaming   |   libavutil      56. 51.100 / 56. 51.100
liveStreaming   |   libavcodec     58. 91.100 / 58. 91.100
liveStreaming   |   libavformat    58. 45.100 / 58. 45.100
liveStreaming   |   libavdevice    58. 10.100 / 58. 10.100
liveStreaming   |   libavfilter     7. 85.100 /  7. 85.100
liveStreaming   |   libavresample   4.  0.  0 /  4.  0.  0
liveStreaming   |   libswscale      5.  7.100 /  5.  7.100
liveStreaming   |   libswresample   3.  7.100 /  3.  7.100
liveStreaming   |   libpostproc    55.  7.100 / 55.  7.100
liveStreaming   | ffmpeg version 4.3-2~18.04.york0 Copyright (c) 2000-2020 the FFmpeg developers
liveStreaming   |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
liveStreaming   |   configuration: --prefix=/usr --extra-version='2~18.04.york0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
liveStreaming   |   libavutil      56. 51.100 / 56. 51.100
liveStreaming   |   libavcodec     58. 91.100 / 58. 91.100
liveStreaming   |   libavformat    58. 45.100 / 58. 45.100
liveStreaming   |   libavdevice    58. 10.100 / 58. 10.100
liveStreaming   |   libavfilter     7. 85.100 /  7. 85.100
liveStreaming   |   libavresample   4.  0.  0 /  4.  0.  0
liveStreaming   |   libswscale      5.  7.100 /  5.  7.100
liveStreaming   |   libswresample   3.  7.100 /  3.  7.100
liveStreaming   |   libpostproc    55.  7.100 / 55.  7.100
liveStreaming   | [x11grab @ 0x56391ad8f200] Stream #0: not enough frames to estimate rate; consider increasing probesize
liveStreaming   | Input #0, x11grab, from ':122':
liveStreaming   |   Duration: N/A, start: 1594468475.202309, bitrate: 1988667 kb/s
liveStreaming   |     Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 1988667 kb/s, 29.97 fps, 1000k tbr, 1000k tbn, 1000k tbc
liveStreaming   | [x11grab @ 0x55fd3e32a6c0] Stream #0: not enough frames to estimate rate; consider increasing probesize
liveStreaming   | Input #0, x11grab, from ':122':
liveStreaming   |   Duration: N/A, start: 1594468475.209156, bitrate: 1988667 kb/s
liveStreaming   |     Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 1988667 kb/s, 29.97 fps, 1000k tbr, 1000k tbn, 1000k tbc
liveStreaming   | Guessed Channel Layout for Input Stream #1.0 : stereo
liveStreaming   | Input #1, alsa, from 'pulse':
liveStreaming   |   Duration: N/A, start: 1594468475.228676, bitrate: 1536 kb/s
liveStreaming   |     Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
liveStreaming   | Guessed Channel Layout for Input Stream #1.0 : stereo
liveStreaming   | Input #1, alsa, from 'pulse':
liveStreaming   |   Duration: N/A, start: 1594468475.227999, bitrate: 1536 kb/s
liveStreaming   |     Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
liveStreaming   | Stream mapping:
liveStreaming   |   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264rgb))
liveStreaming   |   Stream #1:0 -> #0:1 (pcm_s16le (native) -> vorbis (libvorbis))
liveStreaming   | Press [q] to stop, [?] for help
liveStreaming   | [libx264rgb @ 0x56391adb90c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
liveStreaming   | [libx264rgb @ 0x56391adb90c0] profile High 4:4:4 Predictive, level 4.0, 4:4:4 8-bit
liveStreaming   | [libx264rgb @ 0x56391adb90c0] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
liveStreaming   | Output #0, matroska, to '/video/meeting-20200711135428.mkv':
liveStreaming   |   Metadata:
liveStreaming   |     encoder         : Lavf58.45.100
liveStreaming   |     Stream #0:0: Video: h264 (libx264rgb) (H264 / 0x34363248), bgr0(progressive), 1920x1080, q=-1--1, 29.97 fps, 1k tbn, 29.97 tbc
liveStreaming   |     Metadata:
liveStreaming   |       encoder         : Lavc58.91.100 libx264rgb
liveStreaming   |     Side data:
liveStreaming   |       cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
liveStreaming   |     Stream #0:1: Audio: vorbis (libvorbis) (oV[0][0] / 0x566F), 48000 Hz, stereo, fltp
liveStreaming   |     Metadata:
liveStreaming   |       encoder         : Lavc58.91.100 libvorbis
rtmp://a.rtmp.youtube.com/live2: Input/output error0:00.80 bitrate=  47.2kbits/s speed=0.794x    s speed=0.599x  

The streaming does not start, Is there a way I can provide the stream key? If not, what do you think I might be doing wrong?

Thank you so much for taking time to help me.

**Comment by mbile** [comment]
Hello @mtsonline,

Now I can stream the meeting on youtube as well as on Facebook but I don't live user joining the meeting, the live stream on youtube and facebook only shows the first page of the presentation and doesn't show any other action I take like changing the slides, sharing screen. What do you think I am missing here?

Here's the log:

docker-compose up 
Creating network "sadm_default" with the default driver
Creating liveStreaming ... done
Attaching to liveStreaming
liveStreaming   | INFO:root:Starting browser!!
liveStreaming   | INFO:root:streaming intro...
liveStreaming   | ffmpeg version 4.3-2~18.04.york0 Copyright (c) 2000-2020 the FFmpeg developers
liveStreaming   |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
liveStreaming   |   configuration: --prefix=/usr --extra-version='2~18.04.york0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
liveStreaming   |   libavutil      56. 51.100 / 56. 51.100
liveStreaming   |   libavcodec     58. 91.100 / 58. 91.100
liveStreaming   |   libavformat    58. 45.100 / 58. 45.100
liveStreaming   |   libavdevice    58. 10.100 / 58. 10.100
liveStreaming   |   libavfilter     7. 85.100 /  7. 85.100
liveStreaming   |   libavresample   4.  0.  0 /  4.  0.  0
liveStreaming   |   libswscale      5.  7.100 /  5.  7.100
liveStreaming   |   libswresample   3.  7.100 /  3.  7.100
liveStreaming   |   libpostproc    55.  7.100 / 55.  7.100
liveStreaming   | false: No such file or directory
liveStreaming   | INFO:root:Open BBB and hide elements!!
liveStreaming   | INFO:root:create_meeting...
liveStreaming   | INFO:root:get_join_url...
liveStreaming   | INFO:root:saving meeting as /video/meeting-20200711144355.mkv
liveStreaming   | INFO:root:streaming meeting...
liveStreaming   | ffmpeg version 4.3-2~18.04.york0 Copyright (c) 2000-2020 the FFmpeg developers
liveStreaming   |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
liveStreaming   |   configuration: --prefix=/usr --extra-version='2~18.04.york0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
liveStreaming   |   libavutil      56. 51.100 / 56. 51.100
liveStreaming   |   libavcodec     58. 91.100 / 58. 91.100
liveStreaming   |   libavformat    58. 45.100 / 58. 45.100
liveStreaming   |   libavdevice    58. 10.100 / 58. 10.100
liveStreaming   |   libavfilter     7. 85.100 /  7. 85.100
liveStreaming   |   libavresample   4.  0.  0 /  4.  0.  0
liveStreaming   |   libswscale      5.  7.100 /  5.  7.100
liveStreaming   |   libswresample   3.  7.100 /  3.  7.100
liveStreaming   |   libpostproc    55.  7.100 / 55.  7.100
liveStreaming   | ffmpeg version 4.3-2~18.04.york0 Copyright (c) 2000-2020 the FFmpeg developers
liveStreaming   |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
liveStreaming   |   configuration: --prefix=/usr --extra-version='2~18.04.york0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
liveStreaming   |   libavutil      56. 51.100 / 56. 51.100
liveStreaming   |   libavcodec     58. 91.100 / 58. 91.100
liveStreaming   |   libavformat    58. 45.100 / 58. 45.100
liveStreaming   |   libavdevice    58. 10.100 / 58. 10.100
liveStreaming   |   libavfilter     7. 85.100 /  7. 85.100
liveStreaming   |   libavresample   4.  0.  0 /  4.  0.  0
liveStreaming   |   libswscale      5.  7.100 /  5.  7.100
liveStreaming   |   libswresample   3.  7.100 /  3.  7.100
liveStreaming   |   libpostproc    55.  7.100 / 55.  7.100
liveStreaming   | [x11grab @ 0x556f077b1200] Stream #0: not enough frames to estimate rate; consider increasing probesize
liveStreaming   | Input #0, x11grab, from ':122':
liveStreaming   |   Duration: N/A, start: 1594471442.777094, bitrate: 1988667 kb/s
liveStreaming   |     Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 1988667 kb/s, 29.97 fps, 1000k tbr, 1000k tbn, 1000k tbc
liveStreaming   | [x11grab @ 0x5594d06cd6c0] Stream #0: not enough frames to estimate rate; consider increasing probesize
liveStreaming   | Input #0, x11grab, from ':122':
liveStreaming   |   Duration: N/A, start: 1594471442.778702, bitrate: 1988667 kb/s
liveStreaming   |     Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 1988667 kb/s, 29.97 fps, 1000k tbr, 1000k tbn, 1000k tbc
liveStreaming   | Guessed Channel Layout for Input Stream #1.0 : stereo
liveStreaming   | Input #1, alsa, from 'pulse':
liveStreaming   |   Duration: N/A, start: 1594471442.802845, bitrate: 1536 kb/s
liveStreaming   |     Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
liveStreaming   | Stream mapping:
liveStreaming   |   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264rgb))
liveStreaming   |   Stream #1:0 -> #0:1 (pcm_s16le (native) -> vorbis (libvorbis))
liveStreaming   | Press [q] to stop, [?] for help
liveStreaming   | Guessed Channel Layout for Input Stream #1.0 : stereo
liveStreaming   | Input #1, alsa, from 'pulse':
liveStreaming   |   Duration: N/A, start: 1594471442.808915, bitrate: 1536 kb/s
liveStreaming   |     Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
liveStreaming   | [libx264rgb @ 0x556f077db0c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
liveStreaming   | [libx264rgb @ 0x556f077db0c0] profile High 4:4:4 Predictive, level 4.0, 4:4:4 8-bit
liveStreaming   | [libx264rgb @ 0x556f077db0c0] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
liveStreaming   | Output #0, matroska, to '/video/meeting-20200711144355.mkv':
liveStreaming   |   Metadata:
liveStreaming   |     encoder         : Lavf58.45.100
liveStreaming   |     Stream #0:0: Video: h264 (libx264rgb) (H264 / 0x34363248), bgr0(progressive), 1920x1080, q=-1--1, 29.97 fps, 1k tbn, 29.97 tbc
liveStreaming   |     Metadata:
liveStreaming   |       encoder         : Lavc58.91.100 libx264rgb
liveStreaming   |     Side data:
liveStreaming   |       cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
liveStreaming   |     Stream #0:1: Audio: vorbis (libvorbis) (oV[0][0] / 0x566F), 48000 Hz, stereo, fltp
liveStreaming   |     Metadata:
liveStreaming   |       encoder         : Lavc58.91.100 libvorbis
Stream mapping:= 31 q=0.0 size=       5kB time=00:00:02.30 bitrate=  16.4kbits/s speed=0.917x    s speed=0.558x    
liveStreaming   |   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
liveStreaming   |   Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
liveStreaming   | Press [q] to stop, [?] for help
liveStreaming   | [libx264 @ 0x5594d06f7440] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
liveStreaming   | [libx264 @ 0x5594d06f7440] profile Constrained Baseline, level 4.2
liveStreaming   | [libx264 @ 0x5594d06f7440] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=60 keyint_min=6 scenecut=0 intra_refresh=0 rc_lookahead=0 rc=cbr mbtree=0 bitrate=4000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=4000 vbv_bufsize=8000 nal_hrd=cbr filler=1 ip_ratio=1.40 aq=0
liveStreaming   | Output #0, flv, to 'rtmps://live-api-s.facebook.com:443/rtmp/3022186067880282?s_bl=1&s_ps=1&s_sw=0&s_vt=api-s&a=AbxrQ0LONjTl-LSl':
liveStreaming   |   Metadata:
liveStreaming   |     encoder         : Lavf58.45.100
liveStreaming   |     Stream #0:0: Video: h264 (libx264) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1920x1080, q=-1--1, 4000 kb/s, 29.97 fps, 1k tbn, 29.97 tbc
liveStreaming   |     Metadata:
liveStreaming   |       encoder         : Lavc58.91.100 libx264
liveStreaming   |     Side data:
liveStreaming   |       cpb: bitrate max/min/avg: 4000000/0/4000000 buffer size: 8000000 vbv_delay: N/A
liveStreaming   |     Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 160 kb/s
liveStreaming   |     Metadata:
liveStreaming   |       encoder         : Lavc58.91.100 aac

Thanks,

**Comment by mtsonline** [comment]
great that you got it to work.
the stream shows exactly what all other members of the meeting do show.
So if you join in an other window you will / defenitley should - see the same as on the live stream.

not sure how the chromium browser handles javascripts and if bbb uses them to handle the slides though.
But in my understanding that should not make a difference.

**Comment by kaneki666** [comment]
https://github.com/kaneki666/BigBlueButton-liveStreaming/blob/master/examples/docker-compose.yml.example
Pass the stream key like this...if your works let me know..i am stuck too

**Comment by mbile** [comment]
Hi @mtsonline,

> great that you got it to work.
> the stream shows exactly what all other members of the meeting do show.
> So if you join in an other window you will / defenitley should - see the same as on the live stream.

I don't see any user with the name live in the meeting. When I start and run the command: docker-compose up
I am the only one at the meeting.  In the users' list, there is no user called Live who joined the meeting. could this be the issue?

One more thing I have noticed is that even if the meeting ID is wrong, it shows that streaming has started successfully but just shows the first slide of the default presentation in BigBlueButton. is something wrong with the way I am doing it?

> 
> not sure how the chromium browser handles javascripts and if bbb uses them to handle the slides though.
> But in my understanding that should not make a difference.

**Comment by mbile** [comment]
> https://github.com/kaneki666/BigBlueButton-liveStreaming/blob/master/examples/docker-compose.yml.example
> Pass the stream key like this...if your works let me know..i am stuck too

My problem was that the meeting ID I was using was wrong, Just you use the right meeting ID in file docker-compose.yml.

**Comment by mbile** [comment]
Thanks @mtsonline,

It is working now for me. I had a wrong meetingID in the yml file. Thank you again for the help. 
Is there a way I can Start a streaming from the command line. In case I need to stream another meeting other than the one I have in the file.

**Comment by mbile** [comment]
> https://github.com/kaneki666/BigBlueButton-liveStreaming/blob/master/examples/docker-compose.yml.example
> Pass the stream key like this...if your works let me know..i am stuck too

the version of bbb-livestreaming you're using is not the latest version. Make sure you're the latest tag. mine is version: 3.3 and yours is 2.2. You have provided BBB_URL like BBB_URL=http://34.87.179.205/bigbluebutton/api, you are using Http and an IP address. You need to use a domain and get SSL for that domain so that you can connect it securely with https. also, make sure you are using the right meetingID in the docker-compose file. I will be glad to help you any way I can.

**Comment by mtsonline** [comment]
@mbile 
you're welcome :-)
have a look at scheduLight in  the parent git repo.
you can use this to start meetings including liveStreaming. 
if you just need the shell command search in the scheduLight.py class for the subprocess commands to see how to start and stop the liveStreaming ... if you don't find it quickly let me know ;-)
