### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by kaneki666** [aau-zid/BigBlueButton-liveStreaming#44]
root@livestream:/home/shikkhangon_com# docker-compose up 
Creating network "shikkhangon_com_default" with the default driver
Creating liveStreaming ... done
Attaching to liveStreaming
liveStreaming   | INFO:root:Starting browser!!
liveStreaming   | INFO:root:streaming intro...
liveStreaming   | ffmpeg version 4.3-2~18.04.york0 Copyright (c) 2000-2020 the FFmpeg developers
liveStreaming   |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
liveStreaming   |   configuration: --prefix=/usr --extra-version='2~18.04.york0' --toolchain=hardened --libdir=/usr/lib/x86_6
4-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disabl
e-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enabl
e-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribi
di --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libo
penmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --en
able-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --en
able-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --e
nable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --en
able-sdl2 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r 
--enable-libx264 --enable-shared
liveStreaming   |   libavutil      56. 51.100 / 56. 51.100
liveStreaming   |   libavcodec     58. 91.100 / 58. 91.100
liveStreaming   |   libavformat    58. 45.100 / 58. 45.100
liveStreaming   |   libavdevice    58. 10.100 / 58. 10.100
liveStreaming   |   libavfilter     7. 85.100 /  7. 85.100
liveStreaming   |   libavresample   4.  0.  0 /  4.  0.  0
liveStreaming   |   libswscale      5.  7.100 /  5.  7.100
liveStreaming   |   libswresample   3.  7.100 /  3.  7.100
liveStreaming   |   libpostproc    55.  7.100 / 55.  7.100
liveStreaming   | false: No such file or directory
liveStreaming   | INFO:root:Open BBB and hide elements!!
liveStreaming   | INFO:root:create_meeting...
liveStreaming   | INFO:root:get_join_url...
liveStreaming   | Traceback (most recent call last):
liveStreaming   |   File "stream.py", line 157, in <module>
liveStreaming   |     bbb_browser()
liveStreaming   |   File "stream.py", line 75, in bbb_browser
liveStreaming   |     WebDriverWait(browser, selelnium_timeout).until(element)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
liveStreaming   |     raise TimeoutException(message, screen, stacktrace)
liveStreaming   | selenium.common.exceptions.TimeoutException: Message: 
liveStreaming   | 
liveStreaming exited with code 1

fonally some eroor..whats the prb??

**Comment by mtsonline** [comment]
this timeout may occure because you either changed / removed english from the languages so selenium cannot find buttons it seaches, or you disabled the echotest, which selenium is waiting for.
It only happens if selenium cannot find what it searches - and it searches the unchanged bbb  meeting approach.

**Comment by kaneki666** [comment]
yes i have disable echo test..what should i do?

**Comment by mtsonline** [comment]
at the moment we have not implimented any way to handle this.
you either will have to enable the echotest 
or change something in the code.

two ways to change the code to get this running:

* change the join url to directly get into the meeting without popups - this does not work with the python  bbb api call for join urls though - you would have to create the url manually. then you could disable selenium.

* change the elements selenium is searching for - remove the part where it looks for the "with microphone" (not sure how exactly it is called) then it won't wait for it to come up.

hope this helps

**Comment by kaneki666** [comment]
yeah i can do that i have worked with selenium...i will have to edit the stream.py file in my repo and start everything from start right?

**Comment by kaneki666** [comment]
i tried at actually pulls data from this repo not mine? how can i edit the file?

**Comment by kaneki666** [comment]
solved its working

**Comment by shivansh-narayan** [comment]
@kaneki666 How did u solve this ?

**Comment by kaneki666** [comment]
I didn't...i just turned on echo test..it works then

**Comment by alis-maroc** [comment]
Hi
This error still here, tested on two servers without issues !!!

sudo docker-compose up
Starting liveStreaming ... done
Attaching to liveStreaming
liveStreaming   | INFO:root:Starting browser!!
liveStreaming   | INFO:root:Open BBB and hide elements!!
liveStreaming   | INFO:root:create_meeting...
liveStreaming   | INFO:root:get_join_url...
liveStreaming   | Traceback (most recent call last):
liveStreaming   |   File "stream.py", line 157, in <module>
liveStreaming   |     bbb_browser()
liveStreaming   |   File "stream.py", line 75, in bbb_browser
liveStreaming   |     WebDriverWait(browser, selelnium_timeout).until(element)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
liveStreaming   |     raise TimeoutException(message, screen, stacktrace)
liveStreaming   | selenium.common.exceptions.TimeoutException: Message: 
liveStreaming   | 
liveStreaming exited with code 1

Thanks to give solution
