### ISSUE TITLE
Presentation hide!

### ISSUE THREAD

**Issue by kaneki666** [aau-zid/BigBlueButton-liveStreaming#46]
How to hide the presentation...is there any way i can edit the stream.py file and use it...i have forked this project then edited stream.py and created and build repo in docker..still it runs old stream.py file...which branch is docker using

**Comment by sraja415** [comment]
You can hide presentation by deleting the presentation by Moderator. Make sure you don't have a default presentation. This is just a work around given  by Antonio Guirado 

https://groups.google.com/forum/#!msg/bigbluebutton-dev/G8nB8iMia2k/0Ier68SSBgAJ

Read the full thread

**Comment by bayden10** [comment]
Any idea when this might be resolved? Even if the default presentation is minimized it still is shown streaming behind the video.

**Comment by sraja415** [comment]
Remove default presentation. You can pass the  presentation via API (if you so want it) a presentation to be shown when meeting starts. 

Delete any uploaded presentation and your stream will be fine without presentation.

**Comment by madmax2012** [comment]
@kaneki666 Another way would be to add this line 
`browser.find_elements_by_css_selector('button[aria-label="Hide presentation"]')[0].click()`
right above [this line](https://github.com/aau-zid/BigBlueButton-liveStreaming/blob/master/stream.py#L92)

**Comment by mtsonline** [comment]
think this should be realized via css templating ... hoopefully somebody finds the time to impliment this. Not much work. just adding some css example files and the user param that submits it encoded on join.
