### ISSUE TITLE
BBB Issue with screen sharing and voice with youtube streaming

### ISSUE THREAD

**Issue by bhagyavant22** [aau-zid/BigBlueButton-liveStreaming#47]
Hello Team ,
I am getting issue with Following things when i started streaming on youtube.

1. When I share screen from BBB it is not showing in the streaming.
2. When I say something on mic it is also not working in streaming.

But when I share any external video then it works fine in streaming.
any small help is appreciated.
Thanks

**Comment by mtsonline** [comment]
could you solve your problem?
