### ISSUE TITLE
How much resource required to run this container. 

### ISSUE THREAD

**Issue by premryp** [aau-zid/BigBlueButton-liveStreaming#49]
Hello we are using the AWS to run this container in t2.medium

the Usage of CPU is very high 
<img width="1043" alt="Screen Shot 2020-07-15 at 8 31 48 PM" src="https://user-images.githubusercontent.com/67458400/87561453-5afe3200-c6da-11ea-9d2f-5628a2402945.png">

In the above screen shot you are seeing the 87% of CPU just we up the container, once we start the live streaming it crossing to 150% CPU

Also can we run multiple streaming (2 to 3 container with different name and rtmp) in a single t2.medium server

**Comment by mtsonline** [comment]
there are no valid evaluations on how much cpu and memory is required. Please feel free to do some testing and report it - this would help others.
technically you should be able to start multiple streams on the same host, you will have to make sure ports and other capturing will not interfear with eachother.
hth
