### ISSUE TITLE
Boolean ENV parameters BBB_INTRO, BBB_START_MEETING should be checked against "true"

### ISSUE THREAD

**Issue by hbruch** [aau-zid/BigBlueButton-liveStreaming#51]
**Describe the bug**
`startStream.sh`expects a couple of boolean ENV parameters (e.g. `BBB_ENABLE_CHAT`, `BBB_SHOW_CHAT`,`BBB_START_MEETING`, `BBB_INTRO`). 

However, `BBB_INTRO`, `BBB_START_MEETING` are checked against an empty string instead of true.

As a result, chat.py tries to start a meeting, even though BBB_START_MEETING is set to false.

**Comment by mtsonline** [comment]
fixed in the next version. (intro is not boolean)
