### ISSUE TITLE
stream.py: error: unrecognized arguments:

### ISSUE THREAD

**Issue by MonsieurPoutounours** [aau-zid/BigBlueButton-liveStreaming#52]
**Describe the bug**
Trying to launch docker-compose up throw an error.

`Starting liveStreaming
Attaching to liveStreaming
liveStreaming   | usage: stream.py [-h] [-s SERVER] [-p SECRET] [-i ID] [-I INTRO]
liveStreaming   |                  [-B BEGININTROAT] [-E ENDINTROAT] [-l] [-d] [-m] [-S]
liveStreaming   |                  [-A ATTENDEEPASSWORD] [-M MODERATORPASSWORD]
liveStreaming   |                  [-T MEETINGTITLE] [-u USER] [-t TARGET] [-c]
liveStreaming   | stream.py: error: unrecognized arguments:
liveStreaming exited with code 2`

**To Reproduce**
Debian 9 + Docker 
Minimal .yml file 

version: '2'
services:  
 bbb-streamer:    
  image: aauzid/bigbluebutton-livestreaming    
  container_name: liveStreaming    
  environment:      
   - BBB_URL=https://mybbb/bigbluebutton/api      
   - BBB_SECRET=mybbbsecret      
   - BBB_MEETING_ID=xxxxxxx     
   - BBB_STREAM_URL=rtmp://mystreamserver/live/livestream     
   - TZ=Europe/Paris

**Comment by rileyseaburg** [comment]
I've run into the same issue.

**Comment by MonsieurPoutounours** [comment]
Glad to see i am not alone. 
Yet, no one considered the issue in over a month.

**Comment by mtsonline** [comment]
that is not true, but I did not have any idea how to help ;-)
only thing that I can see is, that you did not use version 3 in the docker-compose as we show / suggest in the examples. 
Not sure if this makes any difference though.

have you tried the newest version - does this change something?

**Comment by MonsieurPoutounours** [comment]
Version 3 is unsupported in standard isntallation of Docker in Debian 9.
Using it throws an error.

**Comment by mtsonline** [comment]
ok... have you the newest version then?

the problem is with the arguments supplied. So either you have to less, or a wrong parameter ... the parameters are set in the .sh file depending on which environment variables are set in the docker-compose file.

if the shell script supplies a wrong argument - this only can happen if you have a space in one of your variables. has your meeting id a space?
or any other character that could make troubles?
Or your secret?

you can test which variable is the problem by replacing them one by one ...

**Comment by lordtyrion810** [comment]
Edit: Sorry. Mentioned the wrong variables. Please see my comment below.

Hey! I had the same issue, and what fixed it for me was adding all the variables. For me, the main issue was when I didn't define BBB_START_MEETING. Once I added that it worked fine.

**For example**
environment:
      - BBB_URL= BBB_URL.com/bigbluebutton/api
      - BBB_SECRET=BBB-SECRET
      - BBB_MEETING_ID=MEETING-ID
      - BBB_START_MEETING=false
      - BBB_ATTENDEE_PASSWORD=Test
      - BBB_MODERATOR_PASSWORD=Test
      - BBB_MEETING_TITLE=liveStreaming Test
      - BBB_DOWNLOAD_MEETING=false
      - BBB_INTRO=false
      - BBB_BEGIN_INTRO_AT=00:00:05
      - BBB_END_INTRO_AT=00:00:10
      - BBB_STREAM_URL=STREAM_URL
      - TZ=Europe/Vienna

**Comment by mtsonline** [comment]
Hi, sure you got the error:
"unrecognized arguments: "
when not specifying start_meeting?
this simply does not add "-s" in the shell script and in the python script "-s" is not required.
:-/ 

argParse should add start_meeting regardless wether you specified it or not. either as true (store_true) or false.

**Comment by LordTyrion123** [comment]
Yes. 100%. Even I looked at the python script and figured it should work regardless of whether I define it or not. I'll get some screenshots of both cases and post it here

**Comment by lordtyrion810** [comment]
Sorry. I said the wrong variable. These 2 were causing the issues. When I put these in, it worked fine.
      - BBB_ATTENDEE_PASSWORD=Test
      - BBB_MODERATOR_PASSWORD=Test

**Comment by mtsonline** [comment]
thanks. there was a bug introduced by a PR that should allow spaces in the passwords.
This was reverted in the last version - I suppose you did not check with the newest version?
In the current version this should not happen.
