### ISSUE TITLE
How do i keep it always running?

### ISSUE THREAD

**Issue by kaneki666** [aau-zid/BigBlueButton-liveStreaming#53]
I am using google cloud console...so I start stream by docker conpose up...its stops if i close the shell..is there any way i can keep it running even the shell is closed... sometimes. Electricity might go..and i can't use the chat feature it's not working..how to use the php.chat file

**Comment by mtsonline** [comment]
as stated in the README and as usual with docker containers, run it with docker-compose up -d 
this will start it in the background as process, that will not stop. 
cheers
