### ISSUE TITLE
User "Live" get disconnected after few second

### ISSUE THREAD

**Issue by roneybd85** [aau-zid/BigBlueButton-liveStreaming#54]
I have followed instruction and used default docker-compose.yml with required variables. when i run docker-compose up "Live" user join into the meeting for few seconds and then disappeared ( i can see "live" user appear and disappear in participants list in html5 client  . so in  youtube rmtp server only 1 or 2 seconds recorded . 

Room has been created through moodle . moodle and BBB integration working fine and there are no issue 

BBB version 2.2 

I have followed all standard steps for docker container for streaming .

Is it bug or something that i have missed . I have searched google without any help. Does anyone has any idea what is going on?

Thank you

**Comment by mtsonline** [comment]
...if you have had a look in the issues / closed issues, you would have 
found at least one similar post ;-)

This happens if the echotest could not be passed by selenium.

So either you most likely disabled the echo test in bbb or removed 
english language so the keywords can not be found.


hth

Martin

**Comment by liuwen** [comment]
> ...if you have had a look in the issues / closed issues, you would have found at least one similar post ;-) This happens if the echotest could not be passed by selenium. So either you most likely disabled the echo test in bbb or removed english language so the keywords can not be found. hth Martin

thanks for clearing that out, facing same problem. Though we'd really like to skip `Echo Test` in bbb, and change the default welcome language, in that case should we hack the script regarding selenium in this project to make this work?  is this the only way to go?

**Comment by mtsonline** [comment]
you will have to change the script and remove / adopt selenium so you can disable the echotest and change the language.
The best way to do this would be to change the join url and add userdata parameters to skip the echotest - then the selenium part could be removed.
it would be a bit of work but if you make it clearly, we would appreciate and merge a pull request
