### ISSUE TITLE
How many streams can we create?

### ISSUE THREAD

**Issue by wungaz** [aau-zid/BigBlueButton-liveStreaming#55]
Does it mean we can only have one stream per server? Is it possible to send Meeting_ID as an API so that we can have many streams

**Comment by mtsonline** [comment]
please have a look at the other issues to see how to provide the meeting 
ID via the commandline.

if you have a large server it should be possible to have more streams 
per server, but you may reach the limits regarding cpu and memory quite 
soon....

let us know how many you get to run stable.


cheers
