### ISSUE TITLE
Can you provide Image build script for this code.

### ISSUE THREAD

**Issue by akshaykatale99** [aau-zid/BigBlueButton-liveStreaming#57]
I have made some changes to the script and want to use it for production. it would be great if you share docker Image build script for this code. 

thanks.

**Comment by mtsonline** [comment]
as commented in #56  

to build a local version that you checked out from git, change the image: in the docker-compose to:
```
b bb-streamer:
    container_name: liveStreaming
    build: 
        context: ./
```
then the docker image will be build on your local files instead of fetching it from dockerhub.

this is not specific - you can learn this when you read the docker docs.
