### ISSUE TITLE
Start the stream

### ISSUE THREAD

**Issue by wungaz** [aau-zid/BigBlueButton-liveStreaming#58]
Do you need to manually run _**docker-compose up -d**_ to start the stream?

**Comment by mtsonline** [comment]
how else would you start the docker container?
it is up to you, how you run it, that does not have to be manually. But the command has to be run, otherwise the docker container won't be started.

**Comment by wungaz** [comment]
@mtsonline I have configured meeting ID xyz on the settings but when i start the meeting zyx using API,  the stream does not start automatically

**Comment by wungaz** [comment]
The docker container is up

**Comment by mtsonline** [comment]
...so does it work now?
