### ISSUE TITLE
BBB-Live Installation steps not clear

### ISSUE THREAD

**Issue by createoppurtuinities** [aau-zid/BigBlueButton-liveStreaming#59]
Hi, Thank you so much for bringing this module available. However the installation steps are not clear. I have already installed BBB and greenlight. 

Can you kindly list the quick steps on how to install this module and start our live with youtube and facebook.

Can you please help on the same. I am pretty new with docker and other live meeting. Your inputs will be a great help.

**Comment by ryprfpryr** [comment]
+1 I agree

**Comment by mtsonline** [comment]
what is not clear for you? We provide step by step instructions in the readme ... There is nothing to install, just start the docker-compose that you configured.

cheers

**Comment by createoppurtuinities** [comment]
If we do docker compose then docker will start, However we need to create a container in the docker so that it will fetch the configuration. So a bit of confusion here as the steps say simple say start and stop docker. As these are simple steps need help from your end to understand on few steps on what need to be done to configure BBB-Live and how to end it if we dont need it.

If we need to run parallel live operations then what is the approach.

can you please help spare few minutes to jot down the points here which will help many of them including me.

**Comment by mtsonline** [comment]
maybe you should read some docker guides?

if you - as stated in our readme - run docker-compose up -d 
you do not start docker - you start a docker container. 
there really is not more about it.

as always with docker-compose - to configure just edit the yaml file before you call the docker-compose.

and to stop - also as stated in the readme - use docker-compose down.

did you read the readme? Your questions are clearly answered there.

if you want to stream more than one session at the time you either will have to have more directories with a yaml file or give the settings as arguments instead via the yaml file.... this is all about docker - so please read some docker guides to learn how to use it in an advanced manner.

if you have any specific questions feel free to ask again. thanks.

**Comment by createoppurtuinities** [comment]
can you kindly let us know the command for docker container creation for BBB-Live?

**Comment by mtsonline** [comment]
I am really sorry, but I cannot understand your problem?

you just have to edit the docker-compose.yml with your settings and run docker-compose up -d 
you do not have to create a container, the image will be fetched from dockerhub 

or are you trying to develop and want to change files? If so you really first should learn how to work with docker in general.

**Comment by createoppurtuinities** [comment]
Thanks a lot, i was able to go through docker settings and start it. Can i know do we need to restart BBB after docker restart to start live to youtube?

**Comment by mtsonline** [comment]
no, you do not have to restart bbb.
liveStreaming just acts as any other user and tries to join a meeting.
if the stream does not start / the user disapears from the room shortly after being joined, the reason might be, that the echo test could not be passed. This can be if you disabled the echotest or removed english from the languages.
hth

**Comment by createoppurtuinities** [comment]
Ohh ok, if i disable echo test then i cannot stream my meeting to youtube or facebook? 

related to streaming url shall i need to put my streaming url like this or in this format including the streaming key?

rtmp://a.rtmp.youtube.com/live2/stream/b8ye-mu2p-ptw2-4y0y-1d67

or

Only streaming url like below?

rtmp://a.rtmp.youtube.com/live2/

**Comment by mtsonline** [comment]
yes, at the moment it is not possible to use the streaming if the echotest is disabled.
there would have some lines of code be changed to achieve that - maybe someone could make a pull request with these changes ... there where some users that also needed it in the past.

the key has to be included, correct. You can have a look at the closed issues, there are some threads on youtube and the correct url to use ...

**Comment by createoppurtuinities** [comment]
Hi, I have enabled echo test and english language is already enabled. still live user just joins the meeting and go away in a sec. live is not getting started. can you please help me what could be the reason for the same?

**Comment by mtsonline** [comment]
...check your cpu and memory - it is likely, that you have to low resources, if the stream does not start.
users reported, that 8cpu is a useful minimum

**Comment by createoppurtuinities** [comment]
my server hosted in cloud having 6 CPU and 16 GB ram. here is the log, i create the meeting id from api buddy it says meeting id already exist, when i start the script before api buddy starts it says meeting id already exist, and live user joins for a moment in the meeting for a sec and immediately terminates.  where could be i am wrong and where could be it is giving issues?

please find the log and api buddy test parameters i give for your reference.

![image](https://user-images.githubusercontent.com/61224165/89661890-e7be9900-d8f0-11ea-80f1-c24a5cb905a6.png)

root@testserver:~/BigBlueButton-liveStreaming# docker-compose up
Starting liveStreaming ... done
Attaching to liveStreaming
liveStreaming   | INFO:root:Starting browser!!
liveStreaming   | INFO:root:Open BBB and hide elements!!
liveStreaming   | INFO:root:create_meeting...
liveStreaming   | INFO:root:A meeting already exists with that meeting ID. Please use a different meeting ID.
liveStreaming   | INFO:root:get_join_url...
https://testserver.com/html5client/join?sessionToken=1nn7yytrg3wa8lqg
liveStreaming   | Traceback (most recent call last):
liveStreaming   |   File "stream.py", line 157, in <module>
liveStreaming   |     bbb_browser()
liveStreaming   |   File "stream.py", line 75, in bbb_browser
liveStreaming   |     WebDriverWait(browser, selelnium_timeout).until(element)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
liveStreaming   |     raise TimeoutException(message, screen, stacktrace)
liveStreaming   | selenium.common.exceptions.TimeoutException: Message:
liveStreaming   |
liveStreaming exited with code 1

**Comment by createoppurtuinities** [comment]
Also stream is not getting started and i do not see the stream in youtube.

**Comment by mtsonline** [comment]
as the user exits the room the stream to youtube cannot be up ... ;-)

the log says, that selenium gets a timeout ... as stated, this happens when the user cannot join successfully. mostly when echotest was disabled, or english language is missing.
But also any other change in your system on the flow or labels would cause this.

keep in mind, that selenium expects a untouched bbb and looks for the buttons and labels that normally are shown, to click on them.

did you do any other changes? an access code in the room? or anything else?

in future we want to get ridd of selenium - but there is too less time to get this coded right now ... we would welcome anyone that finds the time to change the login / join to use the "userdata params" to disable echotest and directly join into the meeting without the need for simulate clicks.

**Comment by createoppurtuinities** [comment]
I haven't did any changes in the code rather the labels were changed as per branding like presentation naming was changed to recording, public recording share for every room etc..,  so what could be the solution for my current situation. Yah that's really great if we can get that functionality.

**Comment by mtsonline** [comment]
I have no idea, what else could be the problem. Are you sure the echotest is enabled and english labels are shown?
Did you specify a password in the docker-compose?
are you trying to join as attendee or moderator?

**Comment by createoppurtuinities** [comment]
Yes echo test is enabled. i am also getting thumb nail asking for yes or no. In docker-compose.yml i have given password for modrator and attendee. trying to join as moderator

please find the settings in yml file. any suggestions are appreaciated. 

version: '3.3'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    environment:
      # BigBlueButton Server url:
      - BBB_URL=https://testserver.com/bigbluebutton/api
      # BigBlueButton secret:
      - BBB_SECRET=txbF890Fl0IdaKcBSN0F9cMHtPIba8mDLOEBN8komE
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=testmeet9
      # start meeting (optional):
      - BBB_START_MEETING=false
      # attendee password (optional - has to be set to the attendee password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_ATTENDEE_PASSWORD=IVLHwOBSVmYP
      # moderator password (optional - has to be set to the moderator password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_MODERATOR_PASSWORD=JjeQYksarqLQ
      # meeting title (optional):
      - BBB_MEETING_TITLE=liveStreaming Test
      # download / save BigBlueButton meeting
      - BBB_DOWNLOAD_MEETING=false
      # play intro file (can be a local file in videodata folder e.g. /video/intro.mp4 or a url of a mediastream e.g. https://my.intro.stream)
      - BBB_INTRO=
      # begin the intro at position (optional, e.g. 00:00:05)
      - BBB_BEGIN_INTRO_AT=04:40
      # end intro after (optional, e.g. 01:00:00 - after one hour)
      - BBB_END_INTRO_AT=
      # Media server url:
      - BBB_STREAM_URL=rtmp://a.rtmp.youtube.com/live2/stream/bfgue-mdfp-ptc2-h7tgy-jljhljhl
      # Timezone (default: Europe/Vienna):
      - TZ=Europe/Vienna

    volumes:
      - ./videodata:/video

**Comment by mtsonline** [comment]
please try to get it to run without passwords first - so we reduce the points of fail - remove or comment this:
- BBB_ATTENDEE_PASSWORD=
- BBB_MODERATOR_PASSWORD=JjeQYksarqLQ


and this (you do not have a intro file but try to start it at ...:
- BBB_BEGIN_INTRO_AT=04:40

and are you sure the media url is correct?
- BBB_STREAM_URL=rtmp://a.rtmp.youtube.com/live2/stream/bfgue-mdfp-ptc2-h7tgy-jljhljhl


hth

**Comment by createoppurtuinities** [comment]
Ok will remove password and try. Can we comment intro as well?

Yah I copied the url from youtube studio


   - rtmp://a.rtmp.youtube.com/live2/
   <http://a.rtmp.youtube.com/live2/stream/bfgue-mdfp-ptc2-h7tgy-jljhljhl>

*as the url example for BBB live suggests to add /stream/streamkey*


*I appended the url like this *


   - rtmp://a.rtmp.youtube.com/live2/stream/bfgue-mdfp-ptc2-h7tgy-jljhljh
   <http://a.rtmp.youtube.com/live2/stream/bfgue-mdfp-ptc2-h7tgy-jljhljhl>th

Is this process correct?

**Comment by mtsonline** [comment]
yes you can comment the intro too.

your youtube url seems to be correct ...users reported, it has to have this form:
• BBB_STREAM_URL=rtmp://a.rtmp.youtube.com/live2/stream/XXXXXXXXXXX
