### ISSUE TITLE
start stream error when i  docker-compose up run

### ISSUE THREAD

**Issue by ArminShahamati** [aau-zid/BigBlueButton-liveStreaming#60]
when I run this command 
` docker-compose up`
I have this error and the live stream did not work correctly and I have this error
`root@iranserver ~/stream # docker-compose up
Starting liveStreaming ... done
Attaching to liveStreaming
liveStreaming   | INFO:root:Starting browser!!
liveStreaming   | INFO:root:streaming intro...
liveStreaming   | ffmpeg version 4.3-2~18.04.york0 Copyright (c) 2000-2020 the FFmpeg developers
liveStreaming   |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
liveStreaming   |   configuration: --prefix=/usr --extra-version='2~18.04.york0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
liveStreaming   |   libavutil      56. 51.100 / 56. 51.100
liveStreaming   |   libavcodec     58. 91.100 / 58. 91.100
liveStreaming   |   libavformat    58. 45.100 / 58. 45.100
liveStreaming   |   libavdevice    58. 10.100 / 58. 10.100
liveStreaming   |   libavfilter     7. 85.100 /  7. 85.100
liveStreaming   |   libavresample   4.  0.  0 /  4.  0.  0
liveStreaming   |   libswscale      5.  7.100 /  5.  7.100
liveStreaming   |   libswresample   3.  7.100 /  3.  7.100
liveStreaming   |   libpostproc    55.  7.100 / 55.  7.100
liveStreaming   | false: No such file or directory
liveStreaming   | INFO:root:Open BBB and hide elements!!
liveStreaming   | INFO:root:create_meeting...
liveStreaming   | Traceback (most recent call last):
liveStreaming   |   File "stream.py", line 157, in <module>
liveStreaming   |     bbb_browser()
liveStreaming   |   File "stream.py", line 69, in bbb_browser
liveStreaming   |     create_meeting()
liveStreaming   |   File "stream.py", line 102, in create_meeting
liveStreaming   |     return bbb.create_meeting(args.id, params=create_params)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/bigbluebutton_api_python/bigbluebutton.py", line 47, in create_meeting
liveStreaming   |     response = self.__send_api_request(ApiMethod.CREATE, params)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/bigbluebutton_api_python/bigbluebutton.py", line 135, in __send_api_request
liveStreaming   |     response = urlopen(url).read()
liveStreaming   |   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
liveStreaming   |     return opener.open(url, data, timeout)
liveStreaming   |   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
liveStreaming   |     response = meth(req, response)
liveStreaming   |   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
liveStreaming   |     'http', request, response, code, msg, hdrs)
liveStreaming   |   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
liveStreaming   |     return self._call_chain(*args)
liveStreaming   |   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
liveStreaming   |     result = func(*args)
liveStreaming   |   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
liveStreaming   |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
liveStreaming   | urllib.error.HTTPError: HTTP Error 403: Forbidden
liveStreaming exited with code 1`
**Please Help me**

**Comment by mtsonline** [comment]
you obviously have a wrong bbb url, as you get a 403 forbidden ... or did secure the api.
hth

**Comment by ArminShahamati** [comment]
this is my bbb url
![1](https://user-images.githubusercontent.com/6270065/89673930-800e4b00-d8fc-11ea-9af4-b9bc5c754448.JPG)
 and this is my stream config
![2](https://user-images.githubusercontent.com/6270065/89673953-87cdef80-d8fc-11ea-9e1b-c6c5fbd821d4.JPG)

all of my configurations are correct but I have this error

**Comment by mtsonline** [comment]
can you please replace the image of the url with text? ...
if everything was ok it would work ;-)

**Comment by ArminShahamati** [comment]
I can't Understand 
Can you explain more?

**Comment by mtsonline** [comment]
please post the url as text not a screenshot

**Comment by ArminShahamati** [comment]
this is my docker-compose.yml 
`version: '3.3'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    environment:
      # BigBlueButton Server url:
      - BBB_URL=https://f95.com/bigbluebutton/api
      # BigBlueButton secret:
      - BBB_SECRET=*************************************************
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=random-8647971
      # start meeting (optional):
      - BBB_START_MEETING=false
      # attendee password (optional - has to be set to the attendee password of moodle/greenlight o$
      - BBB_ATTENDEE_PASSWORD=ap
      # moderator password (optional - has to be set to the moderator password of moodle/greenlight$
      - BBB_MODERATOR_PASSWORD=mp
      # meeting title (optional):
      - BBB_MEETING_TITLE=Iran Server Live Stream
      # download / save BigBlueButton meeting
      - BBB_DOWNLOAD_MEETING=false
      # play intro file (can be a local file in videodata folder e.g. /video/intro.mp4 or a url of $
      - BBB_INTRO=false
      # begin the intro at position (optional, e.g. 00:00:05)
      - BBB_BEGIN_INTRO_AT=00:00:05
      # end intro after (optional, e.g. 01:00:00 - after one hour)
      - BBB_END_INTRO_AT=
      # Media server url:`

this is my bbb conf :
` URL: https://f95.com/bigbluebutton/
    Secret: ****************`

**Comment by mtsonline** [comment]
did you configure an intro to be streamed? (in the log it says streaming intro) ...did you try without this? ... maybe the intro file is giving the 403 - not bbb.

**Comment by ArminShahamati** [comment]
yes I test stream server by OBS studio app

**Comment by ArminShahamati** [comment]
how to remove streaming intro ?

**Comment by mtsonline** [comment]
comment the line:
    BBB_INTRO=false 
->
     \# BBB_INTRO=false 

otherwise it tries to stream a file named false.

**Comment by ArminShahamati** [comment]
after comment
` # BBB_INTRO=false`
It still gives the same error as before

**Comment by ArminShahamati** [comment]
`root@iranserver ~/stream # docker-compose up

Starting liveStreaming ... done
Attaching to liveStreaming
liveStreaming   | Traceback (most recent call last):
liveStreaming   |   File "stream.py", line 145, in <module>
liveStreaming   |     while bbb.is_meeting_running(args.id).is_meeting_running() != True:
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/bigbluebutton_api_python/bigbluebutton.py", line 59, in is_meeting_running
liveStreaming   |     response = self.__send_api_request(ApiMethod.IS_MEETING_RUNNING, params)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/bigbluebutton_api_python/bigbluebutton.py", line 135, in __send_api_request
liveStreaming   |     response = urlopen(url).read()
liveStreaming   |   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
liveStreaming   |     return opener.open(url, data, timeout)
liveStreaming   |   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
liveStreaming   |     response = meth(req, response)
liveStreaming   |   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
liveStreaming   |     'http', request, response, code, msg, hdrs)
liveStreaming   |   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
liveStreaming   |     return self._call_chain(*args)
liveStreaming   |   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
liveStreaming   |     result = func(*args)
liveStreaming   |   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
liveStreaming   |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
liveStreaming   | urllib.error.HTTPError: HTTP Error 403: Forbidden
liveStreaming exited with code 1`

**Comment by ArminShahamati** [comment]
Sometimes it gives this error
`root@iranserver ~/stream # docker-compose up

Starting liveStreaming ... done
Attaching to liveStreaming
liveStreaming   | xvfb-run: error: Xvfb failed to start`

**Comment by mtsonline** [comment]
ok these seem to be different problems ...
the first one (creating) happens if you did not start the meeting ...and probably did not configure liveStreaming to start the meeting and join as moderator.

the second one may be caused, because the meeting is running and you configured a password that is not correct. comment the attendee and moderator password lines in the docker-compose - they will be fetched from the running meeting - you just need them if you start the meeting and afterwards want to allow users via greenlight to join. If the room is running you do not need to configure the passwords.

the third one looks like to less cpu or memory.

**Comment by ArminShahamati** [comment]
sorry,
I comment passwords but I have that error too

**Comment by mtsonline** [comment]
please execute the getMeetings script in the examples folder and see what this shows.
and then take the join url from there and try to open this.

**Comment by ArminShahamati** [comment]
I have this 
`<response>
<returncode>SUCCESS</returncode>
<meetings>
<meeting>
<meetingName>live</meetingName>
<meetingID>2e6b650a42f7b8b50fc492f08577de47431eda8c</meetingID>
<internalMeetingID>5ef6924163fa17b706b2237d9ac4d6d6c5837816-1596825913313</internalMeetingID>
<createTime>1596825913313</createTime>
<createDate>Fri Aug 07 23:15:13 IRDT 2020</createDate>
<voiceBridge>55263</voiceBridge>
<dialNumber>613-555-1234</dialNumber>
<attendeePW>zMzqztELGNXC</attendeePW>
<moderatorPW>lguPzSJNigFG</moderatorPW>
<running>true</running>
<duration>0</duration>
<hasUserJoined>true</hasUserJoined>
<recording>true</recording>
<hasBeenForciblyEnded>false</hasBeenForciblyEnded>
<startTime>1596825913425</startTime>
<endTime>0</endTime>
<participantCount>1</participantCount>
<listenerCount>1</listenerCount>
<voiceParticipantCount>0</voiceParticipantCount>
<videoCount>0</videoCount>
<maxUsers>0</maxUsers>
<moderatorCount>1</moderatorCount>
<attendees>
<attendee>
<userID>gl-gqhnrheinrzb</userID>
<fullName>اکبر شهامتی</fullName>
<role>MODERATOR</role>
<isPresenter>true</isPresenter>
<isListeningOnly>true</isListeningOnly>
<hasJoinedVoice>false</hasJoinedVoice>
<hasVideo>false</hasVideo>
<clientType>HTML5</clientType>
</attendee>
</attendees>
<metadata>
<bbb-origin-version>v2</bbb-origin-version>
<bbb-origin-server-name>f95.com</bbb-origin-server-name>
<bbb-origin>Greenlight</bbb-origin>
<gl-listed>false</gl-listed>
</metadata>
<isBreakout>false</isBreakout>
</meeting>
</meetings>
</response>`

**Comment by mtsonline** [comment]
should be fixed in the master branch now.
