### ISSUE TITLE
I did all in the readme and installed and configured. Greenlight front end - I want to know How to start the meeting

### ISSUE THREAD

**Issue by erpsolns** [aau-zid/BigBlueButton-liveStreaming#61]
I did all in the readme and installed and configured. But I dont know How to start the meeting. 
I have few meetings with Greenlight as front end.
I want to use this feature experimentally in those meetings.  How can I do that please?

**Comment by erpsolns** [comment]
Any help in this will be much appreciated.  Thanks in advance.

**Comment by mtsonline** [comment]
Hi,

start the meeting as usual. Just join the meeting via greenlight or whatever is your frontend.
The liveStreaming will be waiting for the meeting to come up, after you started it with docker-compose up -d as stated in the readme.
As soon as you opened the meeting the live user also will join the meeting and the stream starts.
