### ISSUE TITLE
File "stream.py", line 78, in bbb_browser 

### ISSUE THREAD

**Issue by SadeqRouhani** [aau-zid/BigBlueButton-liveStreaming#68]
Hi everyBody.
when i launch composer-up, a user with name: "Live" enters the room.
but after about 10 second, i have this errors:

> liveStreaming   | Traceback (most recent call last):
> liveStreaming   |   File "stream.py", line 164, in <module>
> liveStreaming   |     bbb_browser()
> liveStreaming   |   File "stream.py", line 78, in bbb_browser
> liveStreaming   |     WebDriverWait(browser, selelnium_timeout).until(element)
> liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
> liveStreaming   |     raise TimeoutException(message, screen, stacktrace)
> liveStreaming   | selenium.common.exceptions.TimeoutException: Message: 
> liveStreaming   | 
> liveStreaming exited with code 1

**my com docker-compose.yml file:**

> version: '3.3'
> services:
>   bbb-streamer:
>     image: aauzid/bigbluebutton-livestreaming
>     container_name: liveStreaming
>     environment:
>       # BigBlueButton Server url:
>       - BBB_URL=deleted
>       # BigBlueButton secret:
>       - BBB_SECRET=deleted
>       # BigBlueButton meetingID:
>       - BBB_MEETING_ID=757512c26f
>       # start meeting (optional):
>       - BBB_START_MEETING=false
>       # attendee password (optional - has to be set to the attendee password of moodle/greenlight or any other frontend to allow joining via their links):
>       - BBB_ATTENDEE_PASSWORD=d8e76e8737
>       # moderator password (optional - has to be set to the moderator password of moodle/greenlight or any other frontend to allow joining via their links):
>       - BBB_MODERATOR_PASSWORD=f04cd6fc5c
>       # meeting title (optional):
>       - BBB_MEETING_TITLE=liveStreaming
>       # download / save BigBlueButton meeting
>       - BBB_DOWNLOAD_MEETING=false
>       # play intro file (can be a local file in videodata folder e.g. /video/intro.mp4 or a url of a mediastream e.g. https://my.intro.stream)
>       - BBB_INTRO=false
>       - BBB_AS_MODERATOR=true
>       # begin the intro at position (optional, e.g. 00:00:05)
>       - BBB_BEGIN_INTRO_AT=
>       # end intro after (optional, e.g. 01:00:00 - after one hour)
>       - BBB_END_INTRO_AT=
>       # Media server url:
>       - BBB_STREAM_URL=rtmp://rtmp..............
> 
>       # Timezone (default: Europe/Vienna):
>       - TZ=Europe/Vienna
> 
>     volumes:
>       - ./videodata:/video
> 

**Thank you for your guidance**

**Comment by mtsonline** [comment]
which version are you using?
Please try the new version we released yesterday.

if you set intro to false the file "false" will be searched. comment it or leave it blank if you do not have an intro file.

the as_moderator was removed as it does not make sense and won't work with the new join routine.

let us know, if it works with the newest version ... there was a bug when passwords wheree specified ...

**Comment by SadeqRouhani** [comment]
> which version are you using?
> Please try the new version we released yesterday.

i use latest version and i reinstall it right now and test again but show same errors

> if you set intro to false the file "false" will be searched. comment it or leave it blank if you do not have an intro file.
> the as_moderator was removed as it does not make sense and won't work with the new join routine.
 
this environment was deleted:
- BBB_INTRO=false
- BBB_AS_MODERATOR=true

but nothing changed...

my errors:
`live_streaming  | Traceback (most recent call last):
live_streaming  |   File "stream.py", line 164, in <module>
live_streaming  |     bbb_browser()
live_streaming  |   File "stream.py", line 78, in bbb_browser
live_streaming  |     WebDriverWait(browser, selelnium_timeout).until(element)
live_streaming  |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
live_streaming  |     raise TimeoutException(message, screen, stacktrace)
live_streaming  | selenium.common.exceptions.TimeoutException: Message: `

**Comment by mtsonline** [comment]
sure you use the newest version?
in the logs, is the join url shown right after the "get join url" info message?
What happens when you open this url in your browser?

how did you reinstall it?

**Comment by SadeqRouhani** [comment]
tanks for your response dear @mtsonline 

> sure you use the newest version?

yes i'm sure

> in the logs, is the join url shown right after the "get join url" info message?

yes in latest version i get join url in logs

> What happens when you open this url in your browser?

when i open join url, i join to room and want me get access for play sound.

> how did you reinstall it?

i remove image from docker and then:
`docker pull aauzid/bigbluebutton-livestreaming:latest`

**Comment by mtsonline** [comment]
"when i open join url, i join to room and want me get access for play sound."

that should not be the case. You should get a popup where to choose between join with mic or listen only.
I tried to remove the requirement of clicking on listen only, but there is no way to do that, as the browser either will ask for the choice, or to allow audio/mic.

Did you disable listen only serverwide? That may override the setting supplied in the join url.
Or did you set force_listen_only serverwide? This would cause the same probably.

it is a  pain, that we cannot get ridd of these access dialogues  :-(

**Comment by SadeqRouhani** [comment]
> I tried to remove the requirement of clicking on listen only, but there is no way to do that, as the browser either will ask for the choice, or to allow audio/mic.

when i join room with my api, exactly ask for the choice, or to allow audio/mic.
but when i use logs join url show something else.
in info logs and join url this parameters set:
`?meetingID=757512c26f&fullName=Live&password=d8e76e8737&userdata-bbb_auto_join_audio=true&userdata-bbb_enable_video=false&userdata-bbb_listen_only_mode=true&userdata-bbb_force_listen_only=false&userdata-bbb_skip_check_audio=true`



> Did you disable listen only serverwide? That may override the setting supplied in the join url.
> Or did you set force_listen_only serverwide? This would cause the same probably.

yes i test them but nothing changed.
and then revert them to default...

> it is a pain, that we cannot get ridd of these access dialogues :-(

yees :-(((

**Comment by mtsonline** [comment]
just to be sure, you have english language?
the script is looking for "listen only" so if english is not available it will fail.
I cannot reproduce your problem, :-/ 

I could automatically join with mic but then the browser will ask for the access to the mic / input device so we won't get in either.

what popup exactly shows up with the join url in your setup?

**Comment by SadeqRouhani** [comment]
> the script is looking for "listen only" so if english is not available it will fail.

thanks for your answer.
it's because of bigbluebutton language
