### ISSUE TITLE
Can multiple conferences can also be livestreamed in parallel?

### ISSUE THREAD

**Issue by ramakirankumar** [aau-zid/BigBlueButton-liveStreaming#7]
Hi,

Great to see this module for BBB. Want to reconfirm whether we can live stream multiple conferences at a time?

Thanks and Regards,
KiranKumar

**Comment by mtsonline** [comment]
Hi Kiran,


just start multiple docker container instances. As we have to open a 
browser for each conference, it is not a good idea to do this within one 
container.

Of course you only need one mediaserver, where you can use multiple 
streamKeys for the different conferences.

hth

Martin
