### ISSUE TITLE
Youtube Live - Special Requirements?

### ISSUE THREAD

**Issue by bayden10** [aau-zid/BigBlueButton-liveStreaming#73]
While streaming a live session to Youtube the presentation does not minimize and the stream breaks after only a few minutes. Poor "YouTube is not receiving enough video to maintain smooth streaming" - this happens every 2min.

Video window does not resize in Live Stream even if full screen is applied within the session.

docker logs
```
liveStreaming   | [flv @ 0x557622cdc500] Non-monotonous DTS in output stream 0:1; previous: 1066041, current: 1064974; changing to 1066041. This may result in incorrect timestamps in the output file.

[aac @ 0x557622ce1e80] Queue input is backward in time1.56 bitrate=3350.8kbits/s dup=0 drop=155 speed=0.964x    1 speed=0.962x
[aac @ 0x557622ce1e80] Queue input is backward in time326kB time=00:19:22.46 bitrate=3349.7kbits/s dup=0 drop=155 speed=0.964x
```

bbb v2.2.22
10 CPUs
16GB Mem 
100GB SSD RAID
1GB Full Up&Down
TZ=America/Toronto

Other running images: greenlight / bigbluebutton-exporter / node_exporter 

Streaming from Camera/Chrome High Res with Audio, connection 1GB.

Also why is there a 30sec to 60sec delay to Youtube stream, is this normal with Youtube live streaming?
I did notice a 2 line patch for disabling the Presentation, will this be included in the current master branch soon?

**Comment by mtsonline** [comment]
Hi Jim,

for the patch to be merged, we are waiting for some changes, as far as I can remember ... we'll have a look at it again and see if it can be merged without them though.

regarding your youtube problem... it looks like your system is transcoding to slow, but with 10cpus and 16gb of memory this should not happen :-/ but this seems to cause the delay, which should be arround 10-15 seconds normally.

Could you try to stop the other docker containers for testing and see if it still happens?
could you check your connection to youtube?

resizing the window withing the session does not work, you would have to click within the window to do so.

**Comment by bayden10** [comment]
I was using Grafana to monitor the session and CPU utilization maxed out at 26%, Memory max out at 12GB. Latency response and API was less than 0.2%. What does "click within the window" mean. Connection to Youtube is excellent.

**Comment by mtsonline** [comment]
the stream you send to youtube is a captured screen from a virtual user within the bbb meeting.
So if you want to maximize this window (or a component, as the presentation) you would have to click the specific button within this virtual users window (html5 client) of the bbb meeting.
hope this makes clear what it means and why it is not easy to change the look of what is streamed.

if your consumed resources are that low, I have no idea, what delays that much and even stops the stream.
does the virtual live stream user leave the meeting and the capturing breaks, or does it still capture the meeting and only the stream to youtube stops?
any additional messages in the docker logs?

**Comment by bayden10** [comment]
Hi, no additional logs that I can see and the stream does not break, after 1min of streaming just lags and a warning within the Youtube Live Stream window within the Youtube Studio indicating Poor. While moderating the BBB session I have maximized the video window but the live stream still shows the same sized video window centered from the default load of the session. If I move the video window around in the BBB session it still shows as the same size centered in the Live stream on Youtube.

**Comment by mtsonline** [comment]
as I just said, your window (moderator) is not the streamed window. The streamed window is the one of the virtual user that joins in the session.
If you want to change something you would have the virtual user to change it ... this has to be done within the python script via selenium and you will have to learn how to do that.

no idea what is delaying the transcoding or streaming to youtube though

**Comment by bayden10** [comment]
Hi, Still resize video not shown when logged in to session as participant. 
Here is a complete log of whats happening:
https://pastebin.com/uGRNfzwv

**Comment by mtsonline** [comment]
you do not understand what I say, you cannot login as the streaming user, just the virtual chrome browser / user sees the window that will be streamed - and just this user can change it.
If you login as an user you see a different screen.
If you want to change the screen of the stream you have to change it via selenium / via the cvirtual window in the python script.

regarding the dts time sync problem, it sounds like this:
https://stackoverflow.com/questions/46796992/ffmpeg-flv-0xbeee10-non-monotonous-dts-in-output-stream

you could checkout the repo and start with a local build of the lifeStreaming ...in the stream.py file try the parameters from the answers in the mentioned thread for ffmpeg and see if something changes.
There also may be other parameters that could help - let us know if you find something, we will be happy to merge any pr that improves the streams.

**Comment by harykeyrun** [comment]
Hi, can we control the remote view as a presenter/moderator by sending signal using a websocket to all participants including the virtual/streaming user to resize window, minimize or maximize presentation or align camera options.

**Comment by mtsonline** [comment]
unfortunately bigbluebutton does not support that. 
you would have to impliment it in the system.
cheers
