### ISSUE TITLE
Can't get this to work with vimeo

### ISSUE THREAD

**Issue by stwo-aix** [aau-zid/BigBlueButton-liveStreaming#77]
Hello,

I'm trying to get this to work and I want to stream to vimeo. I have to commit, that I don't have much knowledge about rtmp streams...

The docker is running on a virtual machine different from the bbb-Server. I filled the BBB server information into the compose.yml. The URL (ending with "/bigbluebutton/api"), the secret and the "meeting ID". I guessed this is the code in the invitation link (e.g if the link is https://bbb.example.com/b/bbb-123-abc-def, the meeting id is bbb-123-abc-def). I don't use passwords and intros. 

So first thing is that I don't know if this part of the config is working. How could I test this?
Second thing is: how do I fill in the rtmp-URL? This should be the information where to stream bbb into, correct? So I tried it with youtube and vimeo (while I would definitly prefer vimeo!). But the rtmp-URL of those two websites is some general address like rtmp://a.rtmp.youtube.com/live2 or rtmp://rtmp-global.cloud.vimeo.com/live and you need to fill in the additional stream key somewhere. All other manuals offer two fields, one for the URL and one for the key. But I can only fill in the URL in the compose.yml file.

Is there something I'm missing or doing wrong? Or how would be the vimeo rtmp-Link including the key?

Thank you for your answers.

**Comment by mtsonline** [comment]
Hi,

no, the part in the invite link is just the alias greenlight creates for a meeting. start the meeting via greenlight or your frontend of choice and then run the getMeetings helper  in the examples folder:
examples/get_meetings.py 


the url for youtube e.g. has to include the key:
• BBB_STREAM_URL={youtube-server-url} + / + {Name/Key}

not sure for other platforms, their support should be able to give you the correct syntax to use their service.
cheers
