### ISSUE TITLE
Chinese is not support 

### ISSUE THREAD

**Issue by caijian76** [aau-zid/BigBlueButton-liveStreaming#79]
**Describe the bug**
Chinese displayed are all squares.

**Screenshots**

<img width="389" alt="截屏2020-09-22 上午1 20 29" src="https://user-images.githubusercontent.com/24736690/93799538-d992c500-fc71-11ea-9235-3c851477bee1.png">

**Comment by mtsonline** [comment]
beside the title and name of the users that join the bbb session, the liveStreaming does not interact with language strings at all.
It only captures the meeting - so if there are problems with a language the cause most likely will be somewhere else.

**Comment by caijian76** [comment]
How can chrome in docker display Chinese normally?

**Comment by mtsonline** [comment]
ah, good question. no idea about that.
do you think an language extension is needed therefore? ...sorry, nothing to do with chinese normally.
