### ISSUE TITLE
A few questions before installation

### ISSUE THREAD

**Issue by bijism** [aau-zid/BigBlueButton-liveStreaming#84]
Does this project give us elos.vc output?
How does this project work?

![image](https://user-images.githubusercontent.com/5095139/95044604-b09c1680-06ec-11eb-8e07-54752eb42918.png)

**Comment by bijism** [comment]
I do all the installation steps according to the instructions and you UP the Docker again but it is not seen in BBB.

**Comment by mtsonline** [comment]
I do not understand what you mean with elos ...this is a tool to sttream a BigBlueButton meeting.
And it won't show up in the meeting, it does broadcast the meeting via rtmp to a media server or platform.

**Comment by bijism** [comment]
Hello dear friend.
The elos.vc is a bbb server that has enabled the stream feature.

We have made all the docker-compose.yml settings and have up the docker.
But now how does the stream feature add to our classes?

Thanks for your reply

**Comment by mtsonline** [comment]
if elos.vc features streaming you will have to ask there how to use it.
As I said, this tool just streams the meeting you configured in the docker-compose.yml file to a rtmp server.
it does not integrate in the bbb userinterface.
