### ISSUE TITLE
Audio / video lag

### ISSUE THREAD

**Issue by MonsieurPoutounours** [aau-zid/BigBlueButton-liveStreaming#85]
Hi,

My setup encounter a 5 second audio / video (webcam) lag with every meeting i try to stream to RTMP server. 
Adding CPU or RAM changes nothing (tests show a 50 % ressource usage anyway).
I tried default audio / video options and also @glunardi 's one in #62. 

No lag for users in BBB.

In order to check RTMP server's as a cause, i tried to save meeting into MKV file: video file has lag to.

Can i try other options ? Did someone already had lag between audio and video streams like that ? 

VM : Debian 9, 4 vCPU, 4 GB, Proxmox VM

**Comment by mtsonline** [comment]
as noone seems to have the same issue, I will close this. hope you could find a solution ...
