### ISSUE TITLE
Error with chat_send in stream.py

### ISSUE THREAD

**Issue by thifranc** [aau-zid/BigBlueButton-liveStreaming#89]
Hi, I have install BigBlueButton-liveStreaming and cannot stream with it so far :

chat_send = browser.find_elements_by_css_selector('[aria-label="Send message"]')[0]

I have copied/pasted the URL used by the 'live' user to go and join the room, and I saw that :  
![Screenshot_20201120_105230](https://user-images.githubusercontent.com/17310666/99786523-e53e2300-2b1e-11eb-82e3-24c7035daecd.png)

I feel like the problem comes from the modal poping up, I tried to add :
```
        print(browser.find_elements_by_css_selector('[aria-label="Play audio"]'))
        join_audio = browser.find_elements_by_css_selector('[aria-label="Play audio"]')
        if len(join_audio) > 0:
          join_audio[0].click()

```
Just to see if it would close the modal but it didn't work.

Has anyone got the same problem ?

**Comment by cod3r0k** [comment]
HI I had the same issue. what should I do now?

**Comment by thifranc** [comment]
Hi,
This should be fixed as the PR has been merged since.
You can open a new issue on the project, describing your problem, and explaining your actual state and your 'desired' state.

If you have juste the same issue, you may have old code running ? are you using the latest version available ?
