### ISSUE TITLE
unable to check logs

### ISSUE THREAD

**Issue by karthikindia** [aau-zid/BigBlueButton-liveStreaming#9]
I tried installing the docker
i can see the process running but unable to view the stream
i need to know how to check logs
https://pix.cobrasoftwares.org/image/jRuf
https://pix.cobrasoftwares.org/image/jvWn
output - https://cuetube.in/plugin/Live/?c=jack
need to know what is wrong

**Comment by mtsonline** [comment]
you either can start the docker container with docker-compose up (without -d) then you see the log output on commandline
or you can use docker logs <docker_id>
