### ISSUE TITLE
Integrate with scalelite-BBB-Greenlight

### ISSUE THREAD

**Issue by c0r3dump3d** [aau-zid/BigBlueButton-liveStreaming#92]
Hi, It's possible to integrate BigBlueButton-liveStreaming with a scalelite-Grennlight-BBB instalations?.We have this architecture and we would like to consider the possibility that our users could broadcast to Youtube. 

Would it be possible?

**Comment by mtsonline** [comment]
Hi,
 the lifeStreaming runs separated from BigBlueButton and just joins a meeting like any other user.
So you can use it with your setup.
But you would have to automate or integrate it on your own as the application for now is stand alone.

If you develop some integrations please let the comunity know and share it here or in the bbb mailinglists.
