### ISSUE TITLE
end bbb meeting on liveStreaming exit

### ISSUE THREAD

**Issue by erkinalp** [aau-zid/BigBlueButton-liveStreaming#97]
**Is your feature request related to a problem? Please describe.**
PeerTube has instance and user quotas, which limits the duration that a stream can be continued for it to be archived in its entirety.

**Describe the solution you'd like**
Retrieve the quota from PeerTube side and apply an estimated end time on the BigBlueButton side according to remaining quota.

**Additional context**
PeerTube authentication is required to query quota.

**Comment by mtsonline** [comment]
Hi,

I do not think this should be part of the liveStreaming.
You can do this with a script that starts the liveStreaming, what you have to do anyway for each meeting.
Just make a script that receives the remaining time and send the docker-compose down after the time is over.
If you want to end bbb also at this time you could transfer a end command on liveStreaming shutdown.

This is something that could make sense in the upstream.
So anyone feel free to provide a pull request that introduces 
bbb_end_meeting_on_exit: True|false
as variable and send an end api call to bbb if set to true.

cheers
